#ifndef __HI_M3_VECTOR_H__
#define __HI_M3_VECTOR_H__ 
#define M3_BOOT_VECTORS \
    .word STACK_ENTRY ; \
    .word _start ; \
    .word NmiSR ; \
    .word FaultISR ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word 0 ; \
    .word 0 ; \
    .word 0 ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word 0 ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler ; \
    .word IntDefaultHandler
#endif
