#ifndef __SOC_CPUFREQ_H
#define __SOC_CPUFREQ_H 
#ifndef CPUFREQ_IS_SYNC_DDR
#define CPUFREQ_IS_SYNC_DDR 
#endif
#ifndef CPUFREQ_PLATFORM_HI6930
#define CPUFREQ_PLATFORM_HI6930 
#endif
enum cpufreq_profile{
 BALONG_FREQ_PRO0 = 0,
 BALONG_FREQ_PRO1,
 BALONG_FREQ_PRO2,
 BALONG_FREQ_PRO3,
 BALONG_FREQ_PRO4,
 DC_RESV
};
#endif
