-include $(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk
obj-y	+=	huawei-charger.o

obj-y	+=	chg_charge_task.o
obj-y	+=	chg_charge_stm.o
obj-y	+=	chg_charge_api.o
obj-y	+=	platform/
obj-y	+=	drv/
obj-y	+=	os_adapter/
obj-y	+=	hardware_data/
