/*************************************************************************
CAUTION : This file is Auto Generated by VBA based on 《V750 MBB MACRO_auto_generator.xlsm》.
          So, don't modify this file manually!
****************************************************************************/
#ifndef __MBB_CONFIG_H__
#define __MBB_CONFIG_H__


#ifdef __cplusplus
extern "C"
{
#endif


/******************************* MBB 基础宏定义 *******************************/
#ifndef FEATURE_ON
#define FEATURE_ON 1
#endif

#ifndef FEATURE_OFF
#define FEATURE_OFF 0
#endif

#ifndef YES
#define YES 1
#endif

#ifndef NO
#define NO 0
#endif

#define MBB_COMMON FEATURE_ON  /* 根宏：通用宏开关 */


/****************************************************************************/
/*************************** MBB 特性宏定义开始 *****************************/
/****************************************************************************/
/***************************** 一级宏定义 ***********************************/
#if (FEATURE_ON == MBB_COMMON)
#define    MBB_KEY                             FEATURE_ON         /* 一级宏：按键 */
#define    MBB_KITTING_TOOL                    FEATURE_OFF        /* 一级宏：kittingtool特性宏 */
#define    MBB_MLOG                            FEATURE_ON         /* 一级宏：mobile log */
#define    MBB_CHARGE                          FEATURE_OFF        /* 一级宏：充电 */
#define    MBB_THERMAL_PROTECT                 FEATURE_ON         /* 一级宏：整机温度保护高级路由降速方案 */
#define    MBB_THERMAL_PROTECT_SAR             FEATURE_OFF        /* 一级宏：整机温度保护降最大发射功率方案 */
#define    MBB_WIFI                            FEATURE_ON         /* 一级宏：wifi */
#define    MBB_FAST_ON_OFF                     FEATURE_OFF        /* 一级宏：快速开关机 */
#define    MBB_WPG_COMMON                      FEATURE_ON         /* 一级宏：无线协议代码控制 */
#define    MBB_TOUCHSCREEN                     FEATURE_OFF        /* 一级宏：mbb 触摸屏驱动宏 */
#define    MBB_FEATURE_SD_POLLING              FEATURE_OFF        /* 一级宏：SD卡轮询检测 */
#define    MBB_FEATURE_PHY_NUM                 FEATURE_ON         /* 一级宏：硬件版本号适配 */
#define    MBB_REB                             FEATURE_ON         /* 一级宏：软件可靠性 */
#define    MBB_CTF_COMMON                      FEATURE_OFF        /* 一级宏：CTF特性宏。由于BCM提供的ctf.ko中MBB_CTF_COMMON和MBB_CTF_WIFI_IPV6都是打开的，因此我们代码中这两个宏也应该同时打开或关闭 */
#define    MBB_FEATURE_CAT_MODULE_SET          FEATURE_OFF        /* 一级宏：单板CAT等级 */
#define    MBB_SIMLOCK_FOUR                    FEATURE_ON         /* 一级宏：simlock 4.0 */
#define    MBB_USB                             FEATURE_ON         /* 一级宏：USB */
#define    MBB_DLOAD                           FEATURE_ON         /* 一级宏：升级 */
#define    MBB_LED                             FEATURE_ON         /* 一级宏：LED */
#define    MBB_LCD                             FEATURE_OFF        /* 一级宏：LCD */
#define    MBB_OLED                            FEATURE_OFF        /* 一级宏：OLED */
#define    MBB_SLIC                            FEATURE_ON         /* 一级宏：SLIC特性宏 */
#define    MBB_FEATURE_32K_CLK_SRC             FEATURE_OFF        /* 一级宏：2K时钟源分频 */
#define    MBB_FEATURE_FASTIP                  FEATURE_OFF        /* 一级宏：FastIP */
#define    MBB_ANTENNA                         FEATURE_ON         /* 一级宏：天线切换 */
#define    MBB_FEATURE_ETH                     FEATURE_ON         /* 一级宏：ethernet */
#define    MBB_ECCSTATUS_OPTIMIZE              FEATURE_ON         /* 一级宏：ECC状态获取 文件系统和硬件自检功能需开启 */
#define    MBB_SOFT_POWER_OFF                  FEATURE_ON         /* 一级宏：软关机功能宏 */
#define    MBB_HWTEST                          FEATURE_ON         /* 一级宏：硬件自检功能 */
#define    MBB_FEATURE_FILE_OPERATION          FEATURE_ON         /* 一级宏：MLOG/OFFLINE离线log文件读取工具宏,两者开启任一，此宏都需打开 */
#define    MBB_HSUART                          FEATURE_OFF        /* 一级宏：高速串口功能宏 */
#define    MBB_ATNLPROXY                       FEATURE_OFF        /* 一级宏：AT转发特性宏 */
#define    MBB_MODULE_PM                       FEATURE_OFF        /* 一级宏：模块电源管理特性宏 */
#define    MBB_FEATURE_MODULE_AT               FEATURE_OFF        /* 一级宏：模块AT */
#define    MBB_MODULE_THERMAL_PROTECT          FEATURE_OFF        /* 一级宏：模块温度保护特性宏 */
#define    MBB_FEATURE_DPTF                    FEATURE_OFF        /* 一级宏：CE模块DPTF特性宏 */
#define    MBB_ANTENNA_CONFIGURE               FEATURE_OFF        /* 一级宏：天线控制 */
#define    MBB_NOISETOOL                       FEATURE_OFF        /* 一级宏：NOISE TOOL特性 */
#define    MBB_FEATURE_CIMEI                   FEATURE_OFF        /* 一级宏：customer imei 功能宏 */
#define    MBB_MULTI_CARRIER                   FEATURE_OFF        /* 一级宏：CE模块Multi Carrier宏 */
#define    MBB_FLIGHT_MODE                     FEATURE_OFF        /* 一级宏：飞行模式宏 */
#define    MBB_FEATURE_GPS                     FEATURE_OFF        /* 一级宏：单板是否支持GPS特性 */
#define    MBB_FEATURE_BODYSAR                 FEATURE_OFF        /* 一级宏：BODYSAR宏 */
#define    MBB_PWRCFG                          FEATURE_OFF        /* 一级宏：最大功率可配置特性 */
#define    MBB_FEATURE_NVAUTOBACKUP            FEATURE_ON         /* 一级宏：修改IMEI号触发NV分区备份 功能宏 */
#define    MBB_CLIENT_CODEC                    FEATURE_OFF        /* 一级宏：CODEC配置宏 */
#define    MBB_FEATURE_OFFLINE_LOG             FEATURE_ON         /* 一级宏：离线log功能特性宏 */
#define    MBB_PHY_UART_TEST                   FEATURE_ON         /* 一级宏：产线物理串口回环测试功能 */
#define    MBB_VBUS_POWER_CTRL                 FEATURE_ON         /* 一级宏：Vbus供电控制,包括开关和过流检测,以及提供给应用的节点 */
#define    MBB_AGING_TEST                      FEATURE_OFF        /* 一级宏：归一化老化测试宏 */
#define    MBB_AT_SFEATURE_UMTS_CTRL           FEATURE_OFF        /* 一级宏：AT^SFEATURE返回是否UMTS特性宏 */
#define    MBB_BLUETOOTH                       FEATURE_OFF        /* 一级宏：AT^SFEATURE返回是否BLUETOOTH特性宏 */
#define    MBB_FEATURE_SKU                     FEATURE_OFF        /* 一级宏：SKU特性宏 */
#define    MBB_MEM_CHECK                       FEATURE_OFF        /* 一级宏：mem check功能宏 */
#define    MBB_CPU_FREQ_BOOST                  FEATURE_OFF        /* 一级宏：cpu调频特性宏 */
#define    MBB_RAMDISK_OFFSET                  0x1200000          /* 一级宏：内存中ramdisk与kernel之间的偏移 */
#define    MBB_SIMLOCK_PURE_DIGIT              FEATURE_OFF        /* 一级宏：simlock密码纯数字 */
#define    MBB_NFC                             FEATURE_OFF        /* 一级宏：MBB NFC特性宏 */
#define    MBB_PCIE_CUST_REVERSE               FEATURE_OFF        /* 一级宏：调换PCIE0,PCIE1加载顺序 */
#define    MBB_BATTERY_POWER_PROTECT           FEATURE_ON         /* 一级宏：电池盒功率保护 */
#define    MBB_CARRIER_ADAPTER                 FEATURE_OFF        /* 一级宏：随卡匹配特性宏 */
#define    MBB_RFFE_ANT_TO_MAIN_EXANT          FEATURE_OFF        /* 一级宏：实现通过内外置天线检测去实现有线无线检测配置调用 */
#define    MBB_PCIE1_INNER_CONNECT             FEATURE_OFF        /* 一级宏：WiFi 2.4G PCIE1内部端接 */
#define    MBB_DTS_UNIFORM                     FEATURE_OFF        /* 一级宏：设备树归一特性宏 */
#endif

#if (FEATURE_OFF == MBB_COMMON)
#define    MBB_KEY                             FEATURE_OFF        /* 一级宏：按键 */
#define    MBB_KITTING_TOOL                    FEATURE_OFF        /* 一级宏：kittingtool特性宏 */
#define    MBB_MLOG                            FEATURE_OFF        /* 一级宏：mobile log */
#define    MBB_CHARGE                          FEATURE_OFF        /* 一级宏：充电 */
#define    MBB_THERMAL_PROTECT                 FEATURE_OFF        /* 一级宏：整机温度保护高级路由降速方案 */
#define    MBB_THERMAL_PROTECT_SAR             FEATURE_OFF        /* 一级宏：整机温度保护降最大发射功率方案 */
#define    MBB_WIFI                            FEATURE_OFF        /* 一级宏：wifi */
#define    MBB_FAST_ON_OFF                     FEATURE_OFF        /* 一级宏：快速开关机 */
#define    MBB_WPG_COMMON                      FEATURE_OFF        /* 一级宏：无线协议代码控制 */
#define    MBB_TOUCHSCREEN                     FEATURE_OFF        /* 一级宏：mbb 触摸屏驱动宏 */
#define    MBB_FEATURE_SD_POLLING              FEATURE_OFF        /* 一级宏：SD卡轮询检测 */
#define    MBB_FEATURE_PHY_NUM                 FEATURE_OFF        /* 一级宏：硬件版本号适配 */
#define    MBB_REB                             FEATURE_OFF        /* 一级宏：软件可靠性 */
#define    MBB_CTF_COMMON                      FEATURE_OFF        /* 一级宏：CTF特性宏。由于BCM提供的ctf.ko中MBB_CTF_COMMON和MBB_CTF_WIFI_IPV6都是打开的，因此我们代码中这两个宏也应该同时打开或关闭 */
#define    MBB_FEATURE_CAT_MODULE_SET          FEATURE_OFF        /* 一级宏：单板CAT等级 */
#define    MBB_SIMLOCK_FOUR                    FEATURE_OFF        /* 一级宏：simlock 4.0 */
#define    MBB_USB                             FEATURE_OFF        /* 一级宏：USB */
#define    MBB_DLOAD                           FEATURE_OFF        /* 一级宏：升级 */
#define    MBB_LED                             FEATURE_OFF        /* 一级宏：LED */
#define    MBB_LCD                             FEATURE_OFF        /* 一级宏：LCD */
#define    MBB_OLED                            FEATURE_OFF        /* 一级宏：OLED */
#define    MBB_SLIC                            FEATURE_OFF        /* 一级宏：SLIC特性宏 */
#define    MBB_FEATURE_32K_CLK_SRC             FEATURE_OFF        /* 一级宏：2K时钟源分频 */
#define    MBB_FEATURE_FASTIP                  FEATURE_OFF        /* 一级宏：FastIP */
#define    MBB_ANTENNA                         FEATURE_OFF        /* 一级宏：天线切换 */
#define    MBB_FEATURE_ETH                     FEATURE_OFF        /* 一级宏：ethernet */
#define    MBB_ECCSTATUS_OPTIMIZE              FEATURE_OFF        /* 一级宏：ECC状态获取 文件系统和硬件自检功能需开启 */
#define    MBB_SOFT_POWER_OFF                  FEATURE_OFF        /* 一级宏：软关机功能宏 */
#define    MBB_HWTEST                          FEATURE_OFF        /* 一级宏：硬件自检功能 */
#define    MBB_FEATURE_FILE_OPERATION          FEATURE_OFF        /* 一级宏：MLOG/OFFLINE离线log文件读取工具宏,两者开启任一，此宏都需打开 */
#define    MBB_HSUART                          FEATURE_OFF        /* 一级宏：高速串口功能宏 */
#define    MBB_ATNLPROXY                       FEATURE_OFF        /* 一级宏：AT转发特性宏 */
#define    MBB_MODULE_PM                       FEATURE_OFF        /* 一级宏：模块电源管理特性宏 */
#define    MBB_FEATURE_MODULE_AT               FEATURE_OFF        /* 一级宏：模块AT */
#define    MBB_MODULE_THERMAL_PROTECT          FEATURE_OFF        /* 一级宏：模块温度保护特性宏 */
#define    MBB_FEATURE_DPTF                    FEATURE_OFF        /* 一级宏：CE模块DPTF特性宏 */
#define    MBB_ANTENNA_CONFIGURE               FEATURE_OFF        /* 一级宏：天线控制 */
#define    MBB_NOISETOOL                       FEATURE_OFF        /* 一级宏：NOISE TOOL特性 */
#define    MBB_FEATURE_CIMEI                   FEATURE_OFF        /* 一级宏：customer imei 功能宏 */
#define    MBB_MULTI_CARRIER                   FEATURE_OFF        /* 一级宏：CE模块Multi Carrier宏 */
#define    MBB_FLIGHT_MODE                     FEATURE_OFF        /* 一级宏：飞行模式宏 */
#define    MBB_FEATURE_GPS                     FEATURE_OFF        /* 一级宏：单板是否支持GPS特性 */
#define    MBB_FEATURE_BODYSAR                 FEATURE_OFF        /* 一级宏：BODYSAR宏 */
#define    MBB_PWRCFG                          FEATURE_OFF        /* 一级宏：最大功率可配置特性 */
#define    MBB_FEATURE_NVAUTOBACKUP            FEATURE_OFF        /* 一级宏：修改IMEI号触发NV分区备份 功能宏 */
#define    MBB_CLIENT_CODEC                    FEATURE_OFF        /* 一级宏：CODEC配置宏 */
#define    MBB_FEATURE_OFFLINE_LOG             FEATURE_OFF        /* 一级宏：离线log功能特性宏 */
#define    MBB_PHY_UART_TEST                   FEATURE_OFF        /* 一级宏：产线物理串口回环测试功能 */
#define    MBB_VBUS_POWER_CTRL                 FEATURE_OFF        /* 一级宏：Vbus供电控制,包括开关和过流检测,以及提供给应用的节点 */
#define    MBB_AGING_TEST                      FEATURE_OFF        /* 一级宏：归一化老化测试宏 */
#define    MBB_AT_SFEATURE_UMTS_CTRL           FEATURE_OFF        /* 一级宏：AT^SFEATURE返回是否UMTS特性宏 */
#define    MBB_BLUETOOTH                       FEATURE_OFF        /* 一级宏：AT^SFEATURE返回是否BLUETOOTH特性宏 */
#define    MBB_FEATURE_SKU                     FEATURE_OFF        /* 一级宏：SKU特性宏 */
#define    MBB_MEM_CHECK                       FEATURE_OFF        /* 一级宏：mem check功能宏 */
#define    MBB_CPU_FREQ_BOOST                  FEATURE_OFF        /* 一级宏：cpu调频特性宏 */
#define    MBB_RAMDISK_OFFSET                  FEATURE_OFF        /* 一级宏：内存中ramdisk与kernel之间的偏移 */
#define    MBB_SIMLOCK_PURE_DIGIT              FEATURE_OFF        /* 一级宏：simlock密码纯数字 */
#define    MBB_NFC                             FEATURE_OFF        /* 一级宏：MBB NFC特性宏 */
#define    MBB_PCIE_CUST_REVERSE               FEATURE_OFF        /* 一级宏：调换PCIE0,PCIE1加载顺序 */
#define    MBB_BATTERY_POWER_PROTECT           FEATURE_OFF        /* 一级宏：电池盒功率保护 */
#define    MBB_CARRIER_ADAPTER                 FEATURE_OFF        /* 一级宏：随卡匹配特性宏 */
#define    MBB_RFFE_ANT_TO_MAIN_EXANT          FEATURE_OFF        /* 一级宏：实现通过内外置天线检测去实现有线无线检测配置调用 */
#define    MBB_PCIE1_INNER_CONNECT             FEATURE_OFF        /* 一级宏：WiFi 2.4G PCIE1内部端接 */
#define    MBB_DTS_UNIFORM                     FEATURE_OFF        /* 一级宏：设备树归一特性宏 */
#endif


/********************************* 二级宏定义 *******************************/
#if (FEATURE_ON == MBB_KEY)
#define    MBB_POWER_KEY                       FEATURE_ON         /* 二级宏：power按键 */
#define    MBB_MENU_KEY                        FEATURE_ON         /* 二级宏：menu按键 */
#define    MBB_RESET_KEY                       FEATURE_ON         /* 二级宏：reset按键 */
#define    MBB_WLAN_KEY                        FEATURE_ON         /* 二级宏：wlan按键 */
#endif

#if (FEATURE_OFF == MBB_KEY)
#define    MBB_POWER_KEY                       FEATURE_OFF        /* 二级宏：power按键 */
#define    MBB_MENU_KEY                        FEATURE_OFF        /* 二级宏：menu按键 */
#define    MBB_RESET_KEY                       FEATURE_OFF        /* 二级宏：reset按键 */
#define    MBB_WLAN_KEY                        FEATURE_OFF        /* 二级宏：wlan按键 */
#endif

#if (FEATURE_ON == MBB_CHARGE)
#define    MBB_CHG_PLATFORM_BALONG             FEATURE_ON         /* 二级宏：巴龙充电特性宏 */
#define    MBB_CHG_PLATFORM_QUALCOMM           FEATURE_OFF        /* 二级宏：高通充电特性宏 */
#define    MBB_CHG_BAT_KNOCK_DOWN              FEATURE_ON         /* 二级宏：是否可拆卸电池,ON:是；OFF:不是；不定义：不带电池 */
#define    MBB_CHG_LCD                         FEATURE_OFF        /* 二级宏：LCD产品特性宏 */
#define    MBB_CHG_LED                         FEATURE_OFF        /* 二级宏：LED产品特性宏 */
#define    MBB_CHG_OLED                        FEATURE_OFF        /* 二级宏：OLED产品特性宏 */
#define    MBB_CHG_TOUCH                       FEATURE_OFF        /* 二级宏：TOHCH产品特性宏 */
#define    MBB_CHG_LINUX                       FEATURE_OFF        /* 二级宏：LINUX系统特性宏 */
#define    MBB_CHG_VXWORKS                     FEATURE_OFF        /* 二级宏：LINUX系统特性宏 */
#define    MBB_CHG_REX                         FEATURE_OFF        /* 二级宏：REX系统特性宏 */
#define    MBB_CHG_EXTCHG                      FEATURE_OFF        /* 二级宏：对外充电特性宏 */
#define    MBB_CHG_WIRELESS                    FEATURE_OFF        /* 二级宏：无线充电特性宏 */
#define    MBB_CHG_MC2                         FEATURE_OFF        /* 二级宏：MC2.0特性宏 */
#define    MBB_CHG_COMPENSATE                  FEATURE_OFF        /* 二级宏：工厂补电特性宏 */
#define    MBB_CHG_HVDCP_CHARGE                FEATURE_OFF        /* 二级宏：快速充电特性宏 */
#define    MBB_CHG_BQ25892                     FEATURE_OFF        /* 二级宏：BQ25892充电芯片特性宏 */
#define    MBB_CHG_BQ24196                     FEATURE_OFF        /* 二级宏：BQ24196充电芯片特性宏 */
#define    MBB_CHG_BQ24161                     FEATURE_OFF        /* 二级宏：BQ24161充电芯片特性宏 */
#define    MBB_CHG_MAX8903                     FEATURE_OFF        /* 二级宏：MAX8903充电芯片特性宏 */
#define    MBB_CHG_SCHARGER                    FEATURE_OFF        /* 二级宏：scharger充电芯片特性宏 */
#define    MBB_CHG_WARM_CHARGE                 FEATURE_OFF        /* 二级宏：高温充电特性宏 */
#define    MBB_CHG_MC                          FEATURE_OFF        /* 二级宏：MC特性宏 */
#define    MBB_CHG_POWER_SUPPLY                FEATURE_OFF        /* 二级宏：power supply特性宏 */
#define    MBB_CHG_COULOMETER                  FEATURE_OFF        /* 二级宏：库仑计特性宏 */
#define    MBB_CHG_BQ27510                     FEATURE_OFF        /* 二级宏：外置库仑计特性宏 */
#define    MBB_CHG_HIGH_VOLT_BATT              FEATURE_OFF        /* 二级宏：高压电池特性宏 */
#define    MBB_CHG_BAT_CAPABILITY              3000               /* 二级宏：电池容量 */
#define    MBB_DCM_CUST_CHG_THERMAL            FEATURE_OFF        /* 二级宏：Docomo定制温保方案 */
#define    MBB_CHG_USB_TEMPPT_ILIMIT           FEATURE_OFF        /* 二级宏：USB端口温度保护，前段限流100MA特性宏 */
#define    MBB_CHG_BATT_EXPAND_PROTECT         FEATURE_OFF        /* 二级宏：电池膨胀保护特性宏 */
#endif

#if (FEATURE_OFF == MBB_CHARGE)
#define    MBB_CHG_PLATFORM_BALONG             FEATURE_OFF        /* 二级宏：巴龙充电特性宏 */
#define    MBB_CHG_PLATFORM_QUALCOMM           FEATURE_OFF        /* 二级宏：高通充电特性宏 */
#define    MBB_CHG_BAT_KNOCK_DOWN              FEATURE_OFF        /* 二级宏：是否可拆卸电池,ON:是；OFF:不是；不定义：不带电池 */
#define    MBB_CHG_LCD                         FEATURE_OFF        /* 二级宏：LCD产品特性宏 */
#define    MBB_CHG_LED                         FEATURE_OFF        /* 二级宏：LED产品特性宏 */
#define    MBB_CHG_OLED                        FEATURE_OFF        /* 二级宏：OLED产品特性宏 */
#define    MBB_CHG_TOUCH                       FEATURE_OFF        /* 二级宏：TOHCH产品特性宏 */
#define    MBB_CHG_LINUX                       FEATURE_OFF        /* 二级宏：LINUX系统特性宏 */
#define    MBB_CHG_VXWORKS                     FEATURE_OFF        /* 二级宏：LINUX系统特性宏 */
#define    MBB_CHG_REX                         FEATURE_OFF        /* 二级宏：REX系统特性宏 */
#define    MBB_CHG_EXTCHG                      FEATURE_OFF        /* 二级宏：对外充电特性宏 */
#define    MBB_CHG_WIRELESS                    FEATURE_OFF        /* 二级宏：无线充电特性宏 */
#define    MBB_CHG_MC2                         FEATURE_OFF        /* 二级宏：MC2.0特性宏 */
#define    MBB_CHG_COMPENSATE                  FEATURE_OFF        /* 二级宏：工厂补电特性宏 */
#define    MBB_CHG_HVDCP_CHARGE                FEATURE_OFF        /* 二级宏：快速充电特性宏 */
#define    MBB_CHG_BQ25892                     FEATURE_OFF        /* 二级宏：BQ25892充电芯片特性宏 */
#define    MBB_CHG_BQ24196                     FEATURE_OFF        /* 二级宏：BQ24196充电芯片特性宏 */
#define    MBB_CHG_BQ24161                     FEATURE_OFF        /* 二级宏：BQ24161充电芯片特性宏 */
#define    MBB_CHG_MAX8903                     FEATURE_OFF        /* 二级宏：MAX8903充电芯片特性宏 */
#define    MBB_CHG_SCHARGER                    FEATURE_OFF        /* 二级宏：scharger充电芯片特性宏 */
#define    MBB_CHG_WARM_CHARGE                 FEATURE_OFF        /* 二级宏：高温充电特性宏 */
#define    MBB_CHG_MC                          FEATURE_OFF        /* 二级宏：MC特性宏 */
#define    MBB_CHG_POWER_SUPPLY                FEATURE_OFF        /* 二级宏：power supply特性宏 */
#define    MBB_CHG_COULOMETER                  FEATURE_OFF        /* 二级宏：库仑计特性宏 */
#define    MBB_CHG_BQ27510                     FEATURE_OFF        /* 二级宏：外置库仑计特性宏 */
#define    MBB_CHG_HIGH_VOLT_BATT              FEATURE_OFF        /* 二级宏：高压电池特性宏 */
#define    MBB_CHG_BAT_CAPABILITY              FEATURE_OFF        /* 二级宏：电池容量 */
#define    MBB_DCM_CUST_CHG_THERMAL            FEATURE_OFF        /* 二级宏：Docomo定制温保方案 */
#define    MBB_CHG_USB_TEMPPT_ILIMIT           FEATURE_OFF        /* 二级宏：USB端口温度保护，前段限流100MA特性宏 */
#define    MBB_CHG_BATT_EXPAND_PROTECT         FEATURE_OFF        /* 二级宏：电池膨胀保护特性宏 */
#endif

#if (FEATURE_ON == MBB_THERMAL_PROTECT)
#define    MBB_THERMAL_PROTECT_EXT             FEATURE_OFF        /* 二级宏：整机温度保护第二个温度采集点 */
#endif

#if (FEATURE_OFF == MBB_THERMAL_PROTECT)
#define    MBB_THERMAL_PROTECT_EXT             FEATURE_OFF        /* 二级宏：整机温度保护第二个温度采集点 */
#endif

#if (FEATURE_ON == MBB_WIFI)
#define    MBB_WIFI_CHIP1                      bcm4360            /* 二级宏：该宏控制编译哪款芯片.芯片目录命名规则为厂商+编号如：rtl8129, bcm43217,这是和对应的驱动目录名称要一样的。 */
#define    MBB_WIFI_CHIP2                      FEATURE_OFF        /* 二级宏：该宏控制编译哪款芯片.芯片目录命名规则为厂商+编号如：rtl8129, bcm43217,这是和对应的驱动目录名称要一样的。 */
#define    MBB_WIFI_BCM_RFCAL                  FEATURE_ON         /* 二级宏：CPE双博通芯片射频校准宏 */
#endif

#if (FEATURE_OFF == MBB_WIFI)
#define    MBB_WIFI_CHIP1                      FEATURE_OFF        /* 二级宏：该宏控制编译哪款芯片.芯片目录命名规则为厂商+编号如：rtl8129, bcm43217,这是和对应的驱动目录名称要一样的。 */
#define    MBB_WIFI_CHIP2                      FEATURE_OFF        /* 二级宏：该宏控制编译哪款芯片.芯片目录命名规则为厂商+编号如：rtl8129, bcm43217,这是和对应的驱动目录名称要一样的。 */
#define    MBB_WIFI_BCM_RFCAL                  FEATURE_OFF        /* 二级宏：CPE双博通芯片射频校准宏 */
#endif

#if (FEATURE_ON == MBB_WPG_COMMON)
#define    MBB_WPG_AT_CMD_FILTER               FEATURE_ON         /* 二级宏：屏蔽AT命令宏 */
#define    MBB_WPG_AT_CMD_ALLOW                FEATURE_ON         /* 二级宏：二级白名单 */
#define    MBB_TELSTRA_CUSTOMSIZE              FEATURE_OFF        /* 二级宏：澳大利亚Telstra运营商定制 */
#define    MBB_PCVOICE                         FEATURE_OFF        /* 二级宏：PC语音 */
#define    MBB_WPG_NWTIME                      FEATURE_ON         /* 二级宏：时间管理特性 */
#define    MBB_WPG_VCOM                        FEATURE_ON         /* 二级宏：VCOM特性 */
#define    MBB_WPG_DIAL                        FEATURE_ON         /* 二级宏：拨号特性，默认必须打开 */
#define    MBB_WPG_HCSQ                        FEATURE_ON         /* 二级宏：AT命令HCSQ */
#define    MBB_WPG_AT_DEBUG                    FEATURE_ON         /* 二级宏：AT命令调试 */
#define    MBB_WPG_DLCK                        FEATURE_ON         /* 二级宏：设备锁 */
#define    MBB_WPG_SMSREGST                    FEATURE_ON         /* 二级宏：短信自注册 */
#define    MBB_WPG_NWSCAN                      FEATURE_ON         /* 二级宏：NWSCAN */
#define    MBB_WPG_LTERSRP                     FEATURE_ON         /* 二级宏：LTERSRP */
#define    MBB_WPG_HFREQINFO                   FEATURE_ON         /* 二级宏：HFREQINFO命令 */
#define    MBB_WPG_DATACLASS                   FEATURE_ON         /* 二级宏：DATACLASS命令 */
#define    MBB_WPG_DUAL_IMSI                   FEATURE_ON         /* 二级宏：双IMSI切换 */
#define    MBB_WPG_SYSCFGEX                    FEATURE_ON         /* 二级宏：SYSCFGEX定制 */
#define    MBB_WPG_AT                          FEATURE_ON         /* 二级宏：AT特性 */
#define    MBB_WPG_CPBS                        FEATURE_ON         /* 二级宏：CPBS命令 */
#define    MBB_WPG_SYSINFOEX                   FEATURE_ON         /* 二级宏：SYSINFOEX命令 */
#define    MBB_WPG_RSSI                        FEATURE_ON         /* 二级宏：RSSI上报控制 */
#define    MBB_WPG_CSIM                        FEATURE_ON         /* 二级宏：CSIM命令 */
#define    MBB_WPG_CFUN                        FEATURE_ON         /* 二级宏：CFUN定制命令 */
#define    MBB_WPG_SWITCHGW                    FEATURE_ON         /* 二级宏：网关切换 */
#define    MBB_WPG_OPEN_PCUI_RETRY             FEATURE_ON         /* 二级宏：打开PCUI口是进行多次尝试 */
#define    MBB_WPG_RELIABILITY                 FEATURE_OFF        /* 二级宏：可靠性 */
#define    MBB_WPG_CERSSI                      FEATURE_ON         /* 二级宏：CERSSI上报 */
#define    MBB_WPG_STANDBY_NO_REPORT           FEATURE_ON         /* 二级宏：A核休眠不上报特性 */
#define    MBB_WPG_LED_FLASH                   FEATURE_ON         /* 二级宏：闪灯的定制 */
#define    MBB_WPG_GID1_CHECK                  FEATURE_ON         /* 二级宏：GID1检查定制 */
#define    MBB_WPG_DEAD_SIMLOCK                FEATURE_ON         /* 二级宏：永久锁特性 */
#define    MBB_WPG_TIMPIN                      FEATURE_ON         /* 二级宏：TIM的PIN码显示定制 */
#define    MBB_WPG_ROAM                        FEATURE_ON         /* 二级宏：漫游 */
#define    MBB_WPG_OPNAME                      FEATURE_ON         /* 二级宏：运营商名称 */
#define    MBB_WPG_EHPLMN                      FEATURE_ON         /* 二级宏：EHPLMN */
#define    MBB_WPG_RPLMN_DISABLE_ACT           FEATURE_ON         /* 二级宏：RPLMN Disable ACT特性 */
#define    MBB_WPG_PLMNSERCH                   FEATURE_ON         /* 二级宏：搜网 */
#define    MBB_WPG_PLMNSERCH_MAN2AUTO          FEATURE_ON         /* 二级宏：手动搜网开机变成自动搜网定制 */
#define    MBB_WPG_PLMNSERCH_NOCARE_MCC        FEATURE_ON         /* 二级宏：VPLMN回选不考虑特定MCC定制 */
#define    MBB_WPG_EPLMN                       FEATURE_ON         /* 二级宏：EPLMN定制 */
#define    MBB_WPG_XDN                         FEATURE_ON         /* 二级宏：XDN定制 */
#define    MBB_WPG_IMSI_POLLING                FEATURE_ON         /* 二级宏：IMSI轮训检查定制 */
#define    MBB_WPG_WAKE_LOCK_DELAY             FEATURE_ON         /* 二级宏：AT上报延迟睡眠特性 */
#define    MBB_WPG_STK                         FEATURE_ON         /* 二级宏：STK问题修改 */
#define    MBB_WPG_SE13_LIST                   FEATURE_ON         /* 二级宏：SE13列表定制 */
#define    MBB_WPG_FIXED_APN                   FEATURE_ON         /* 二级宏：固定APN定制 */
#define    MBB_WPG_USIM                        FEATURE_ON         /* 二级宏：USIM相关修改 */
#define    MBB_WPG_SIMLOCK                     FEATURE_ON         /* 二级宏：SIMLOCK定制 */
#define    MBB_WPG_HP_IN_EH_NO_ROAM            FEATURE_ON         /* 二级宏：HPLMN在EHPLMN列表中不显示漫游定制 */
#define    MBB_WPG_SPEC_PLMN_NO_ROAM           FEATURE_ON         /* 二级宏：特殊PLMN不显示漫游定制 */
#define    MBB_WPG_ROAM_WHITE_LIST             FEATURE_ON         /* 二级宏：漫游白名单定制 */
#define    MBB_WPG_PCM                         FEATURE_OFF        /* 二级宏：PCM语音 */
#define    MBB_WPG_3GPP_STK                    FEATURE_OFF        /* 二级宏：标准STK */
#define    MBB_WPG_MEMORY_OP                   FEATURE_ON         /* 二级宏：内存优化 */
#define    MBB_WPG_WIN8_STK                    FEATURE_OFF        /* 二级宏：WIN8 上标准STK适配 */
#define    MBB_WPG_ECALL                       FEATURE_OFF        /* 二级宏：ECALL */
#define    MBB_WPG_AC                          FEATURE_OFF        /* 二级宏：模块AC特性宏 */
#define    MBB_WPG_FREQLOCK                    FEATURE_OFF        /* 二级宏：模块锁频特性宏 */
#define    MBB_WPG_SIM_SWITCH                  FEATURE_OFF        /* 二级宏：模块SIMSWITCH特性宏 */
#define    MBB_WPG_CELLLOCK                    FEATURE_OFF        /* 二级宏：模块小区锁特性宏 */
#define    MBB_WPG_FD                          FEATURE_OFF        /* 二级宏：Fast_Dromancy特性宏 */
#define    MBB_WPG_CPBREADY                    FEATURE_OFF        /* 二级宏：CPBREADY特性宏 */
#define    MBB_WPG_TRUST_SNUM                  FEATURE_OFF        /* 二级宏：短信白名单特性宏 */
#define    MBB_WPG_SBB_RRCSTAT                 FEATURE_OFF        /* 二级宏：AT命令^RRCSTAT */
#define    MBB_WPG_HFEATURESTAT                FEATURE_ON         /* 二级宏：HFEATURESTAT命令 */
#define    MBB_WPG_TDD_FDD_CHANGE_SBB          FEATURE_OFF        /* 二级宏：SBB的定制特性，完成FDD only到TDD only的切换，切换过程修改FGI和Band信息 */
#define    MBB_SBM_E5_CUSTOMSIZE               FEATURE_OFF        /* 二级宏：软银定制E5宏 */
#define    MBB_WPG_CELLROAM                    FEATURE_OFF        /* 二级宏：CELLROAM特性宏 */
#define    MBB_DCM_E5_CUSTOMSIZE               FEATURE_OFF        /* 二级宏：DoCoMo协议定制特性宏 */
#define    MBB_WPG_OM_FILTER                   FEATURE_ON         /* 二级宏：DIAG OM白名单（HIDS,HIMS） */
#define    MBB_WPG_KDDI_SIMLOCK_FREE           FEATURE_OFF        /* 二级宏：kddi SIMLOCK黑名单特性定制 */
#define    MBB_WPG_KDDI_APN_MATCH              FEATURE_OFF        /* 二级宏：AU和UQ默认APN自适配定制 */
#define    MBB_WPG_KDDI_HS_HSA_MODE            FEATURE_OFF        /* 二级宏：KDDI HS/HS+A模式切换用户名控制字符定制特性 */
#define    MBB_WPG_VOLTE_CPE                   FEATURE_ON         /* 二级宏：CPE VOLTE特性宏，VOLTE相关的APN的NV从恢复出厂列表删除 MBB_WPG_COMMON */
#define    MBB_WPG_HISTORYFREQ                 FEATURE_ON         /* 二级宏：保存历史频点NV添加到恢复出厂列表中 */
#define    MBB_WPG_CA_SWITCH                   FEATURE_OFF        /* 二级宏：KDDI 控制CA开关特性 */
#define    MBB_WPG_RAT_BAND_PRIORITY           FEATURE_OFF        /* 二级宏：增加AT支持调整/查询RAT及BAND优先级顺序 */
#define    MBB_WPG_CELLLOCK_CPE                FEATURE_OFF        /* 二级宏：CPE 锁小区特性 */
#define    MBB_CUS_LTE_BAND_CHANGE             FEATURE_ON         /* 二级宏：NV9017放入恢复出厂列表 */
#define    MBB_WPG_KDDI_HCSQ_FOR_LED           FEATURE_OFF        /* 二级宏：kddi CPE led信号显示优化 */
#define    MBB_WPG_WIRELESSPARAM               FEATURE_ON         /* 二级宏：无线参数获取 */
#define    MBB_WPG_LTE_NETSCAN                 FEATURE_OFF        /* 二级宏：4G的netscan功能实现 */
#endif

#if (FEATURE_OFF == MBB_WPG_COMMON)
#define    MBB_WPG_AT_CMD_FILTER               FEATURE_OFF        /* 二级宏：屏蔽AT命令宏 */
#define    MBB_WPG_AT_CMD_ALLOW                FEATURE_OFF        /* 二级宏：二级白名单 */
#define    MBB_TELSTRA_CUSTOMSIZE              FEATURE_OFF        /* 二级宏：澳大利亚Telstra运营商定制 */
#define    MBB_PCVOICE                         FEATURE_OFF        /* 二级宏：PC语音 */
#define    MBB_WPG_NWTIME                      FEATURE_OFF        /* 二级宏：时间管理特性 */
#define    MBB_WPG_VCOM                        FEATURE_OFF        /* 二级宏：VCOM特性 */
#define    MBB_WPG_DIAL                        FEATURE_OFF        /* 二级宏：拨号特性，默认必须打开 */
#define    MBB_WPG_HCSQ                        FEATURE_OFF        /* 二级宏：AT命令HCSQ */
#define    MBB_WPG_AT_DEBUG                    FEATURE_OFF        /* 二级宏：AT命令调试 */
#define    MBB_WPG_DLCK                        FEATURE_OFF        /* 二级宏：设备锁 */
#define    MBB_WPG_SMSREGST                    FEATURE_OFF        /* 二级宏：短信自注册 */
#define    MBB_WPG_NWSCAN                      FEATURE_OFF        /* 二级宏：NWSCAN */
#define    MBB_WPG_LTERSRP                     FEATURE_OFF        /* 二级宏：LTERSRP */
#define    MBB_WPG_HFREQINFO                   FEATURE_OFF        /* 二级宏：HFREQINFO命令 */
#define    MBB_WPG_DATACLASS                   FEATURE_OFF        /* 二级宏：DATACLASS命令 */
#define    MBB_WPG_DUAL_IMSI                   FEATURE_OFF        /* 二级宏：双IMSI切换 */
#define    MBB_WPG_SYSCFGEX                    FEATURE_OFF        /* 二级宏：SYSCFGEX定制 */
#define    MBB_WPG_AT                          FEATURE_OFF        /* 二级宏：AT特性 */
#define    MBB_WPG_CPBS                        FEATURE_OFF        /* 二级宏：CPBS命令 */
#define    MBB_WPG_SYSINFOEX                   FEATURE_OFF        /* 二级宏：SYSINFOEX命令 */
#define    MBB_WPG_RSSI                        FEATURE_OFF        /* 二级宏：RSSI上报控制 */
#define    MBB_WPG_CSIM                        FEATURE_OFF        /* 二级宏：CSIM命令 */
#define    MBB_WPG_CFUN                        FEATURE_OFF        /* 二级宏：CFUN定制命令 */
#define    MBB_WPG_SWITCHGW                    FEATURE_OFF        /* 二级宏：网关切换 */
#define    MBB_WPG_OPEN_PCUI_RETRY             FEATURE_OFF        /* 二级宏：打开PCUI口是进行多次尝试 */
#define    MBB_WPG_RELIABILITY                 FEATURE_OFF        /* 二级宏：可靠性 */
#define    MBB_WPG_CERSSI                      FEATURE_OFF        /* 二级宏：CERSSI上报 */
#define    MBB_WPG_STANDBY_NO_REPORT           FEATURE_OFF        /* 二级宏：A核休眠不上报特性 */
#define    MBB_WPG_LED_FLASH                   FEATURE_OFF        /* 二级宏：闪灯的定制 */
#define    MBB_WPG_GID1_CHECK                  FEATURE_OFF        /* 二级宏：GID1检查定制 */
#define    MBB_WPG_DEAD_SIMLOCK                FEATURE_OFF        /* 二级宏：永久锁特性 */
#define    MBB_WPG_TIMPIN                      FEATURE_OFF        /* 二级宏：TIM的PIN码显示定制 */
#define    MBB_WPG_ROAM                        FEATURE_OFF        /* 二级宏：漫游 */
#define    MBB_WPG_OPNAME                      FEATURE_OFF        /* 二级宏：运营商名称 */
#define    MBB_WPG_EHPLMN                      FEATURE_OFF        /* 二级宏：EHPLMN */
#define    MBB_WPG_RPLMN_DISABLE_ACT           FEATURE_OFF        /* 二级宏：RPLMN Disable ACT特性 */
#define    MBB_WPG_PLMNSERCH                   FEATURE_OFF        /* 二级宏：搜网 */
#define    MBB_WPG_PLMNSERCH_MAN2AUTO          FEATURE_OFF        /* 二级宏：手动搜网开机变成自动搜网定制 */
#define    MBB_WPG_PLMNSERCH_NOCARE_MCC        FEATURE_OFF        /* 二级宏：VPLMN回选不考虑特定MCC定制 */
#define    MBB_WPG_EPLMN                       FEATURE_OFF        /* 二级宏：EPLMN定制 */
#define    MBB_WPG_XDN                         FEATURE_OFF        /* 二级宏：XDN定制 */
#define    MBB_WPG_IMSI_POLLING                FEATURE_OFF        /* 二级宏：IMSI轮训检查定制 */
#define    MBB_WPG_WAKE_LOCK_DELAY             FEATURE_OFF        /* 二级宏：AT上报延迟睡眠特性 */
#define    MBB_WPG_STK                         FEATURE_OFF        /* 二级宏：STK问题修改 */
#define    MBB_WPG_SE13_LIST                   FEATURE_OFF        /* 二级宏：SE13列表定制 */
#define    MBB_WPG_FIXED_APN                   FEATURE_OFF        /* 二级宏：固定APN定制 */
#define    MBB_WPG_USIM                        FEATURE_OFF        /* 二级宏：USIM相关修改 */
#define    MBB_WPG_SIMLOCK                     FEATURE_OFF        /* 二级宏：SIMLOCK定制 */
#define    MBB_WPG_HP_IN_EH_NO_ROAM            FEATURE_OFF        /* 二级宏：HPLMN在EHPLMN列表中不显示漫游定制 */
#define    MBB_WPG_SPEC_PLMN_NO_ROAM           FEATURE_OFF        /* 二级宏：特殊PLMN不显示漫游定制 */
#define    MBB_WPG_ROAM_WHITE_LIST             FEATURE_OFF        /* 二级宏：漫游白名单定制 */
#define    MBB_WPG_PCM                         FEATURE_OFF        /* 二级宏：PCM语音 */
#define    MBB_WPG_3GPP_STK                    FEATURE_OFF        /* 二级宏：标准STK */
#define    MBB_WPG_MEMORY_OP                   FEATURE_OFF        /* 二级宏：内存优化 */
#define    MBB_WPG_WIN8_STK                    FEATURE_OFF        /* 二级宏：WIN8 上标准STK适配 */
#define    MBB_WPG_ECALL                       FEATURE_OFF        /* 二级宏：ECALL */
#define    MBB_WPG_AC                          FEATURE_OFF        /* 二级宏：模块AC特性宏 */
#define    MBB_WPG_FREQLOCK                    FEATURE_OFF        /* 二级宏：模块锁频特性宏 */
#define    MBB_WPG_SIM_SWITCH                  FEATURE_OFF        /* 二级宏：模块SIMSWITCH特性宏 */
#define    MBB_WPG_CELLLOCK                    FEATURE_OFF        /* 二级宏：模块小区锁特性宏 */
#define    MBB_WPG_FD                          FEATURE_OFF        /* 二级宏：Fast_Dromancy特性宏 */
#define    MBB_WPG_CPBREADY                    FEATURE_OFF        /* 二级宏：CPBREADY特性宏 */
#define    MBB_WPG_TRUST_SNUM                  FEATURE_OFF        /* 二级宏：短信白名单特性宏 */
#define    MBB_WPG_SBB_RRCSTAT                 FEATURE_OFF        /* 二级宏：AT命令^RRCSTAT */
#define    MBB_WPG_HFEATURESTAT                FEATURE_OFF        /* 二级宏：HFEATURESTAT命令 */
#define    MBB_WPG_TDD_FDD_CHANGE_SBB          FEATURE_OFF        /* 二级宏：SBB的定制特性，完成FDD only到TDD only的切换，切换过程修改FGI和Band信息 */
#define    MBB_SBM_E5_CUSTOMSIZE               FEATURE_OFF        /* 二级宏：软银定制E5宏 */
#define    MBB_WPG_CELLROAM                    FEATURE_OFF        /* 二级宏：CELLROAM特性宏 */
#define    MBB_DCM_E5_CUSTOMSIZE               FEATURE_OFF        /* 二级宏：DoCoMo协议定制特性宏 */
#define    MBB_WPG_OM_FILTER                   FEATURE_OFF        /* 二级宏：DIAG OM白名单（HIDS,HIMS） */
#define    MBB_WPG_KDDI_SIMLOCK_FREE           FEATURE_OFF        /* 二级宏：kddi SIMLOCK黑名单特性定制 */
#define    MBB_WPG_KDDI_APN_MATCH              FEATURE_OFF        /* 二级宏：AU和UQ默认APN自适配定制 */
#define    MBB_WPG_KDDI_HS_HSA_MODE            FEATURE_OFF        /* 二级宏：KDDI HS/HS+A模式切换用户名控制字符定制特性 */
#define    MBB_WPG_VOLTE_CPE                   FEATURE_OFF        /* 二级宏：CPE VOLTE特性宏，VOLTE相关的APN的NV从恢复出厂列表删除 MBB_WPG_COMMON */
#define    MBB_WPG_HISTORYFREQ                 FEATURE_OFF        /* 二级宏：保存历史频点NV添加到恢复出厂列表中 */
#define    MBB_WPG_CA_SWITCH                   FEATURE_OFF        /* 二级宏：KDDI 控制CA开关特性 */
#define    MBB_WPG_RAT_BAND_PRIORITY           FEATURE_OFF        /* 二级宏：增加AT支持调整/查询RAT及BAND优先级顺序 */
#define    MBB_WPG_CELLLOCK_CPE                FEATURE_OFF        /* 二级宏：CPE 锁小区特性 */
#define    MBB_CUS_LTE_BAND_CHANGE             FEATURE_OFF        /* 二级宏：NV9017放入恢复出厂列表 */
#define    MBB_WPG_KDDI_HCSQ_FOR_LED           FEATURE_OFF        /* 二级宏：kddi CPE led信号显示优化 */
#define    MBB_WPG_WIRELESSPARAM               FEATURE_OFF        /* 二级宏：无线参数获取 */
#define    MBB_WPG_LTE_NETSCAN                 FEATURE_OFF        /* 二级宏：4G的netscan功能实现 */
#endif

#if (FEATURE_ON == MBB_TOUCHSCREEN)
#define    MBB_TOUCHSCREEN_MELFAS              FEATURE_OFF        /* 二级宏：melfas touch驱动 */
#define    MBB_TOUCHSCREEN_MSTAR               FEATURE_OFF        /* 二级宏：mstar touch驱动 */
#define    MBB_TOUCHSCREEN_FOCAL               FEATURE_OFF        /* 二级宏：focal touch驱动 */
#endif

#if (FEATURE_OFF == MBB_TOUCHSCREEN)
#define    MBB_TOUCHSCREEN_MELFAS              FEATURE_OFF        /* 二级宏：melfas touch驱动 */
#define    MBB_TOUCHSCREEN_MSTAR               FEATURE_OFF        /* 二级宏：mstar touch驱动 */
#define    MBB_TOUCHSCREEN_FOCAL               FEATURE_OFF        /* 二级宏：focal touch驱动 */
#endif

#if (FEATURE_ON == MBB_CTF_COMMON)
#define    MBB_CTF_WIFI_IPV6                   FEATURE_OFF        /* 二级宏：CTF是否支持IPv6 */
#define    MBB_CTF_WAN_QUEUE                   FEATURE_ON         /* 二级宏：WAN */
#endif

#if (FEATURE_OFF == MBB_CTF_COMMON)
#define    MBB_CTF_WIFI_IPV6                   FEATURE_OFF        /* 二级宏：CTF是否支持IPv6 */
#define    MBB_CTF_WAN_QUEUE                   FEATURE_OFF        /* 二级宏：WAN */
#endif

#if (FEATURE_ON == MBB_USB)
#define    MBB_USB_MULTICONFIG                 FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_SECURITY                    FEATURE_ON         /* 二级宏：USB */
#define    MBB_USB_SD                          FEATURE_ON         /* 二级宏：USB */
#define    MBB_USB_PORT_AUTH                   FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CPE                         FEATURE_ON         /* 二级宏：USB */
#define    MBB_USB_E5                          FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_HILINK                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_STICK                       FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_WINGLE                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_SOLUTION                    FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CAPABILITY_THREE            FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CHARGE                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_TYPEC                       FEATURE_OFF        /* 二级宏：USB */
#endif

#if (FEATURE_OFF == MBB_USB)
#define    MBB_USB_MULTICONFIG                 FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_SECURITY                    FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_SD                          FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_PORT_AUTH                   FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CPE                         FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_E5                          FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_HILINK                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_STICK                       FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_WINGLE                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_SOLUTION                    FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CAPABILITY_THREE            FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_CHARGE                      FEATURE_OFF        /* 二级宏：USB */
#define    MBB_USB_TYPEC                       FEATURE_OFF        /* 二级宏：USB */
#endif

#if (FEATURE_ON == MBB_DLOAD)
#define    MBB_DLOAD_BALONG                    FEATURE_ON         /* 二级宏：balong和高通差异 */
#define    MBB_DLOAD_LED                       FEATURE_ON         /* 二级宏：升级代码led闪灯 */
#define    MBB_DLOAD_LCD                       FEATURE_OFF        /* 二级宏：升级代码lcd显示 */
#define    MBB_DLOAD_BBOU                      FEATURE_ON         /* 二级宏：在线升级 */
#define    MBB_DLOAD_JFFS2                     FEATURE_OFF        /* 二级宏：分区为jffs2文件系统(如webui分区） */
#define    MBB_DLOAD_SDUP                      FEATURE_OFF        /* 二级宏：SD卡升级 */
#define    MBB_DLOAD_HILINK                    FEATURE_OFF        /* 二级宏：hilink升级 */
#define    MBB_DLOAD_WINGLE                    FEATURE_OFF        /* 二级宏：wingle升级 */
#define    MBB_DLOAD_SOLUTION                  FEATURE_OFF        /* 二级宏：solution升级 */
#define    MBB_DLOAD_STICK                     FEATURE_OFF        /* 二级宏：STICK升级 */
#define    MBB_DLOAD_MCPEUP                    FEATURE_ON         /* 二级宏：AP+Modem形态CPE升级 */
#define    MBB_DLOAD_E5                        FEATURE_OFF        /* 二级宏：E5升级 */
#define    MBB_DLOAD_VER_VERIFY                FEATURE_ON         /* 二级宏：安全升级v1.3宏 */
#define    MBB_DLOAD_AUTO_UPDATE               FEATURE_ON         /* 二级宏：自动恢复升级宏 */
#define    MBB_DLOAD_AUTO_FLAG                 FEATURE_ON         /* 二级宏：配合应用层自动升级功能，底层记录自动升级标记 */
#define    MBB_DLOAD_COMMON_DPART              FEATURE_OFF        /* 二级宏：通用双备份宏 */
#define    MBB_DLOAD_RECORD_BAD                FEATURE_OFF        /* 二级宏：原始坏块记录功能宏 */
#define    MBB_DLOAD_OEM_PART_IM               FEATURE_ON         /* 二级宏：OEM分区升级改进方案宏 */
#endif

#if (FEATURE_OFF == MBB_DLOAD)
#define    MBB_DLOAD_BALONG                    FEATURE_OFF        /* 二级宏：balong和高通差异 */
#define    MBB_DLOAD_LED                       FEATURE_OFF        /* 二级宏：升级代码led闪灯 */
#define    MBB_DLOAD_LCD                       FEATURE_OFF        /* 二级宏：升级代码lcd显示 */
#define    MBB_DLOAD_BBOU                      FEATURE_OFF        /* 二级宏：在线升级 */
#define    MBB_DLOAD_JFFS2                     FEATURE_OFF        /* 二级宏：分区为jffs2文件系统(如webui分区） */
#define    MBB_DLOAD_SDUP                      FEATURE_OFF        /* 二级宏：SD卡升级 */
#define    MBB_DLOAD_HILINK                    FEATURE_OFF        /* 二级宏：hilink升级 */
#define    MBB_DLOAD_WINGLE                    FEATURE_OFF        /* 二级宏：wingle升级 */
#define    MBB_DLOAD_SOLUTION                  FEATURE_OFF        /* 二级宏：solution升级 */
#define    MBB_DLOAD_STICK                     FEATURE_OFF        /* 二级宏：STICK升级 */
#define    MBB_DLOAD_MCPEUP                    FEATURE_OFF        /* 二级宏：AP+Modem形态CPE升级 */
#define    MBB_DLOAD_E5                        FEATURE_OFF        /* 二级宏：E5升级 */
#define    MBB_DLOAD_VER_VERIFY                FEATURE_OFF        /* 二级宏：安全升级v1.3宏 */
#define    MBB_DLOAD_AUTO_UPDATE               FEATURE_OFF        /* 二级宏：自动恢复升级宏 */
#define    MBB_DLOAD_AUTO_FLAG                 FEATURE_OFF        /* 二级宏：配合应用层自动升级功能，底层记录自动升级标记 */
#define    MBB_DLOAD_COMMON_DPART              FEATURE_OFF        /* 二级宏：通用双备份宏 */
#define    MBB_DLOAD_RECORD_BAD                FEATURE_OFF        /* 二级宏：原始坏块记录功能宏 */
#define    MBB_DLOAD_OEM_PART_IM               FEATURE_OFF        /* 二级宏：OEM分区升级改进方案宏 */
#endif

#if (FEATURE_ON == MBB_LED)
#define    MBB_LED_DR                          FEATURE_ON         /* 二级宏：DR灯 */
#define    MBB_FEATURE_M2M_LED                 FEATURE_OFF        /* 二级宏：M2M LED */
#define    MBB_LED_GPIO                        FEATURE_ON         /* 二级宏：GPIO灯 */
#endif

#if (FEATURE_OFF == MBB_LED)
#define    MBB_LED_DR                          FEATURE_OFF        /* 二级宏：DR灯 */
#define    MBB_FEATURE_M2M_LED                 FEATURE_OFF        /* 二级宏：M2M LED */
#define    MBB_LED_GPIO                        FEATURE_OFF        /* 二级宏：GPIO灯 */
#endif

#if (FEATURE_ON == MBB_LCD)
#define    MBB_LCD_CLOCKWISE_90                FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转90度 */
#define    MBB_LCD_CLOCKWISE_180               FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转180度 */
#define    MBB_LCD_CLOCKWISE_270               FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转270度 */
#define    MBB_LCD_LANDSCAPE                   FEATURE_OFF        /* 二级宏：LCD的屏幕是横屏还是竖屏 */
#endif

#if (FEATURE_OFF == MBB_LCD)
#define    MBB_LCD_CLOCKWISE_90                FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转90度 */
#define    MBB_LCD_CLOCKWISE_180               FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转180度 */
#define    MBB_LCD_CLOCKWISE_270               FEATURE_OFF        /* 二级宏：让LCD显示顺时针旋转270度 */
#define    MBB_LCD_LANDSCAPE                   FEATURE_OFF        /* 二级宏：LCD的屏幕是横屏还是竖屏 */
#endif

#if (FEATURE_ON == MBB_FEATURE_FASTIP)
#define    MBB_FEATURE_FASTIP_IPV6             FEATURE_ON         /* 二级宏：FastIP 对IPv6的支持 */
#define    MBB_FEATURE_FASTIP_WAN_QUEUE        FEATURE_ON         /* 二级宏：FastIP 使能WAN侧队列 */
#endif

#if (FEATURE_OFF == MBB_FEATURE_FASTIP)
#define    MBB_FEATURE_FASTIP_IPV6             FEATURE_OFF        /* 二级宏：FastIP 对IPv6的支持 */
#define    MBB_FEATURE_FASTIP_WAN_QUEUE        FEATURE_OFF        /* 二级宏：FastIP 使能WAN侧队列 */
#endif

#if (FEATURE_ON == MBB_FEATURE_ETH)
#define    MBB_FEATURE_ETH_PHY                 FEATURE_OFF        /* 二级宏：RGMII口接PHY芯片 */
#define    MBB_FEATURE_ETH_SWITCH              FEATURE_ON         /* 二级宏：RGMII口接SWITCH芯片 */
#define    MBB_FEATURE_ETH_WAN_MIRROR          FEATURE_ON         /* 二级宏：镜像抓包 */
#endif

#if (FEATURE_OFF == MBB_FEATURE_ETH)
#define    MBB_FEATURE_ETH_PHY                 FEATURE_OFF        /* 二级宏：RGMII口接PHY芯片 */
#define    MBB_FEATURE_ETH_SWITCH              FEATURE_OFF        /* 二级宏：RGMII口接SWITCH芯片 */
#define    MBB_FEATURE_ETH_WAN_MIRROR          FEATURE_OFF        /* 二级宏：镜像抓包 */
#endif

#if (FEATURE_ON == MBB_HSUART)
#define    MBB_HSUART_CMUX                     FEATURE_OFF        /* 二级宏：基于高速串口的CMUX功能 */
#define    MBB_HSUART_AT                       FEATURE_OFF        /* 二级宏：基于高速串口的AT功能修改都在此宏内包含 */
#endif

#if (FEATURE_OFF == MBB_HSUART)
#define    MBB_HSUART_CMUX                     FEATURE_OFF        /* 二级宏：基于高速串口的CMUX功能 */
#define    MBB_HSUART_AT                       FEATURE_OFF        /* 二级宏：基于高速串口的AT功能修改都在此宏内包含 */
#endif

#if (FEATURE_ON == MBB_MODULE_PM)
#define    MBB_MODULE_M3_PM                    FEATURE_OFF        /* 二级宏：模块电源管理特性宏 */
#endif

#if (FEATURE_OFF == MBB_MODULE_PM)
#define    MBB_MODULE_M3_PM                    FEATURE_OFF        /* 二级宏：模块电源管理特性宏 */
#endif

#if (FEATURE_ON == MBB_ANTENNA_CONFIGURE)
#define    MBB_ANTENNA_MODE                    FEATURE_OFF        /* 二级宏：主分集天线控制 */
#define    MBB_ANTENNA_TUNER                   FEATURE_OFF        /* 二级宏：调谐天线 */
#endif

#if (FEATURE_OFF == MBB_ANTENNA_CONFIGURE)
#define    MBB_ANTENNA_MODE                    FEATURE_OFF        /* 二级宏：主分集天线控制 */
#define    MBB_ANTENNA_TUNER                   FEATURE_OFF        /* 二级宏：调谐天线 */
#endif

#if (FEATURE_ON == MBB_FEATURE_GPS)
#define    MBB_FEATURE_GPS_UART                FEATURE_OFF        /* 二级宏：BB芯片与GPS通信使用UART口 */
#endif

#if (FEATURE_OFF == MBB_FEATURE_GPS)
#define    MBB_FEATURE_GPS_UART                FEATURE_OFF        /* 二级宏：BB芯片与GPS通信使用UART口 */
#endif

#if (FEATURE_ON == MBB_CPU_FREQ_BOOST)
#define    MBB_TOUCH_BOOST                     FEATURE_OFF        /* 二级宏：touch调频特性宏 */
#define    MBB_KEY_BOOST                       FEATURE_OFF        /* 二级宏：按键调频特性宏 */
#endif

#if (FEATURE_OFF == MBB_CPU_FREQ_BOOST)
#define    MBB_TOUCH_BOOST                     FEATURE_OFF        /* 二级宏：touch调频特性宏 */
#define    MBB_KEY_BOOST                       FEATURE_OFF        /* 二级宏：按键调频特性宏 */
#endif

#if (FEATURE_ON == MBB_NFC)
#define    MBB_NFC_PARSE_URL                   FEATURE_OFF        /* 二级宏：NFC驱动解析URL宏 */
#endif

#if (FEATURE_OFF == MBB_NFC)
#define    MBB_NFC_PARSE_URL                   FEATURE_OFF        /* 二级宏：NFC驱动解析URL宏 */
#endif

#if (FEATURE_ON == MBB_BATTERY_POWER_PROTECT)
#define    BATTBOX_VOLT_THRESHOLD              1660               /* 二级宏：电池盒在位门限值 */
#endif

#if (FEATURE_OFF == MBB_BATTERY_POWER_PROTECT)
#define    BATTBOX_VOLT_THRESHOLD              FEATURE_OFF        /* 二级宏：电池盒在位门限值 */
#endif

#if (FEATURE_ON == MBB_DTS_UNIFORM)
#endif

#if (FEATURE_OFF == MBB_DTS_UNIFORM)
#endif



/****************************** 三级宏定义 *************************************/
#if (FEATURE_ON == MBB_TELSTRA_CUSTOMSIZE)
#define    MBB_T3402_TIMER_CTL                 FEATURE_ON         /* 三级宏：T3402超时后才能enable LTE */
#define    MBB_DIAL_REJ_50_51_CTL              FEATURE_ON         /* 三级宏：LTE注册网络以#50或#51拒绝，UE不应发起另一种类型的PDN承载 */
#endif

#if (FEATURE_OFF == MBB_TELSTRA_CUSTOMSIZE)
#define    MBB_T3402_TIMER_CTL                 FEATURE_OFF        /* 三级宏：T3402超时后才能enable LTE */
#define    MBB_DIAL_REJ_50_51_CTL              FEATURE_OFF        /* 三级宏：LTE注册网络以#50或#51拒绝，UE不应发起另一种类型的PDN承载 */
#endif

#if (FEATURE_ON == MBB_TOUCHSCREEN_MELFAS)
#define    MBB_TP_FIRMWARE_UPDATE              FEATURE_OFF        /* 三级宏：是否需要支持TP的升级功能 */
#endif

#if (FEATURE_OFF == MBB_TOUCHSCREEN_MELFAS)
#define    MBB_TP_FIRMWARE_UPDATE              FEATURE_OFF        /* 三级宏：是否需要支持TP的升级功能 */
#endif

#if (FEATURE_ON == MBB_FEATURE_ETH_SWITCH)
#define    MBB_FEATURE_ETH_SWITCH_8363         FEATURE_ON         /* 三级宏：RGMII接口SWITCH863芯片 */
#define    MBB_FEATURE_ETH_SWITCH_V1310        FEATURE_OFF        /* 三级宏：RGMII接口SWITCHRTL8363NV-VB芯片 */
#define    MBB_FEATURE_ETH_SWITCH_SVLAN        FEATURE_OFF        /* 三级宏：SWITCH svlan功能 */
#define    MBB_RTK_RGMII_RX_DELAY              4                  /* 三级宏：lan switch侧RGMII rx clk delay参数，参数范围0-7，共2ns */
#endif

#if (FEATURE_OFF == MBB_FEATURE_ETH_SWITCH)
#define    MBB_FEATURE_ETH_SWITCH_8363         FEATURE_OFF        /* 三级宏：RGMII接口SWITCH863芯片 */
#define    MBB_FEATURE_ETH_SWITCH_V1310        FEATURE_OFF        /* 三级宏：RGMII接口SWITCHRTL8363NV-VB芯片 */
#define    MBB_FEATURE_ETH_SWITCH_SVLAN        FEATURE_OFF        /* 三级宏：SWITCH svlan功能 */
#define    MBB_RTK_RGMII_RX_DELAY              FEATURE_OFF        /* 三级宏：lan switch侧RGMII rx clk delay参数，参数范围0-7，共2ns */
#endif

#if (FEATURE_ON == MBB_WPG_NWTIME)
#define    MBB_WPG_CCLK                        FEATURE_ON         /* 三级宏：CCLK特性定制 */
#endif

#if (FEATURE_OFF == MBB_WPG_NWTIME)
#define    MBB_WPG_CCLK                        FEATURE_OFF        /* 三级宏：CCLK特性定制 */
#endif

#if (FEATURE_ON == MBB_WPG_DIAL)
#define    MBB_WPG_SHARE_APN                   FEATURE_OFF        /* 三级宏：无线协议拨号共享APN宏 */
#define    MBB_FEATURE_BIP                     FEATURE_ON         /* 三级宏：BIP特性 */
#define    MBB_FEATURE_BIP_TEST                FEATURE_ON         /* 三级宏：BIP特性测试宏 */
#define    MBB_FEATURE_GATEWAY                 FEATURE_OFF        /* 三级宏：适配网关特性测试宏 */
#define    MBB_WPG_PDPSTATUS                   FEATURE_OFF        /* 三级宏：PDPSTATUS主动上报特性定制 */
#endif

#if (FEATURE_OFF == MBB_WPG_DIAL)
#define    MBB_WPG_SHARE_APN                   FEATURE_OFF        /* 三级宏：无线协议拨号共享APN宏 */
#define    MBB_FEATURE_BIP                     FEATURE_OFF        /* 三级宏：BIP特性 */
#define    MBB_FEATURE_BIP_TEST                FEATURE_OFF        /* 三级宏：BIP特性测试宏 */
#define    MBB_FEATURE_GATEWAY                 FEATURE_OFF        /* 三级宏：适配网关特性测试宏 */
#define    MBB_WPG_PDPSTATUS                   FEATURE_OFF        /* 三级宏：PDPSTATUS主动上报特性定制 */
#endif

#if (FEATURE_ON == MBB_WPG_GID1_CHECK)
#define    MBB_WPG_SBB_SIMLOCK                 FEATURE_OFF        /* 三级宏：软银SIMLOCK定制 */
#endif

#if (FEATURE_OFF == MBB_WPG_GID1_CHECK)
#define    MBB_WPG_SBB_SIMLOCK                 FEATURE_OFF        /* 三级宏：软银SIMLOCK定制 */
#endif

#if (FEATURE_ON == MBB_WPG_OPNAME)
#define    MBB_WPG_EE_OP_NAME                  FEATURE_ON         /* 三级宏：英国EE运营商名称定制 */
#define    MBB_WPG_COPN                        FEATURE_ON         /* 三级宏：COPN */
#define    MBB_WPG_SPN                         FEATURE_ON         /* 三级宏：SPN */
#define    MBB_WPG_PNN_OPL                     FEATURE_ON         /* 三级宏：PNN与OPL先关 */
#define    MBB_WPG_CRPN                        FEATURE_ON         /* 三级宏：CRPN */
#define    MBB_WPG_EONS                        FEATURE_ON         /* 三级宏：EONS命令 */
#define    MBB_WPG_NWNAME                      FEATURE_OFF        /* 三级宏：NWNAME使用 */
#endif

#if (FEATURE_OFF == MBB_WPG_OPNAME)
#define    MBB_WPG_EE_OP_NAME                  FEATURE_OFF        /* 三级宏：英国EE运营商名称定制 */
#define    MBB_WPG_COPN                        FEATURE_OFF        /* 三级宏：COPN */
#define    MBB_WPG_SPN                         FEATURE_OFF        /* 三级宏：SPN */
#define    MBB_WPG_PNN_OPL                     FEATURE_OFF        /* 三级宏：PNN与OPL先关 */
#define    MBB_WPG_CRPN                        FEATURE_OFF        /* 三级宏：CRPN */
#define    MBB_WPG_EONS                        FEATURE_OFF        /* 三级宏：EONS命令 */
#define    MBB_WPG_NWNAME                      FEATURE_OFF        /* 三级宏：NWNAME使用 */
#endif

#if (FEATURE_ON == MBB_SBM_E5_CUSTOMSIZE)
#define    MBB_FEATURE_SBM_DATAROAMING         FEATURE_OFF        /* 三级宏：软银定制漫游特性宏 */
#define    MBB_FEATURE_SBM_APN_MATCH           FEATURE_OFF        /* 三级宏：软银APN自适配的特性宏 */
#endif

#if (FEATURE_OFF == MBB_SBM_E5_CUSTOMSIZE)
#define    MBB_FEATURE_SBM_DATAROAMING         FEATURE_OFF        /* 三级宏：软银定制漫游特性宏 */
#define    MBB_FEATURE_SBM_APN_MATCH           FEATURE_OFF        /* 三级宏：软银APN自适配的特性宏 */
#endif

#if (FEATURE_ON == MBB_DCM_E5_CUSTOMSIZE)
#define    MBB_FEATURE_DCM_54MIN_TIMER         FEATURE_OFF        /* 三级宏：DoCoMo 54min定时器disable LTE 的特性宏 */
#define    MBB_FEATURE_DCM_MNC_COMPARE         FEATURE_OFF        /* 三级宏：DoCoMo 3位MNC特性定制宏 */
#define    MBB_FEATURE_DCM_SE13                FEATURE_OFF        /* 三级宏：DoCoMo 定制SE13列表的宏 */
#endif

#if (FEATURE_OFF == MBB_DCM_E5_CUSTOMSIZE)
#define    MBB_FEATURE_DCM_54MIN_TIMER         FEATURE_OFF        /* 三级宏：DoCoMo 54min定时器disable LTE 的特性宏 */
#define    MBB_FEATURE_DCM_MNC_COMPARE         FEATURE_OFF        /* 三级宏：DoCoMo 3位MNC特性定制宏 */
#define    MBB_FEATURE_DCM_SE13                FEATURE_OFF        /* 三级宏：DoCoMo 定制SE13列表的宏 */
#endif



/******************************************************************************/
/***************************** MBB 特性宏定义结束 *****************************/
/******************************************************************************/


#ifdef __cplusplus
}
#endif
#endif /*__MBB_CONFIG_H__ */
