EXTRA_CFLAGS += -I$(srctree)/drivers/huawei_nfc/huawei_nfc_i2c_driver

obj-y    +=    drvi2cm24sr.o
obj-y    +=    drvm24sr.o
obj-y    +=    libm24sr.o
obj-y    +=    libndef.o
obj-y    +=    libndeftext.o
obj-y    +=    libndefuri.o
obj-y    +=    libndefwifi.o
obj-y    +=    libtagtype4.o
