obj-$(CONFIG_BALONG_SPE_SIM) += spe_sim_objs.o
spe_sim_objs-y	:= spe_sim_intr_debug.o spe_sim_entry_debug.o spe_sim_sch_debug.o spe_sim_td.o spe_sim_rd.o spe_sim_ncm.o spe_sim_reg.o spe_sim_debug.o spe_sim_rndis.o

