/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2013-2015. All rights reserved.
 *
 * mobile@huawei.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
/*************************************************************************
CAUTION : This file is Auto Generated by VBA based on 《MBB_AT_whitelist_auto_generator.xlsm》.
          So, don't modify this file manually!
****************************************************************************/


/******************************* 引用头文件 *******************************/
#include "MbbAtCmdFilter.h"





/****************************************************************************/
/*************************** MBB AT 一级白名单列表开始 **********************/
/****************************************************************************/
const VOS_CHAR *gszFilterCmdTable[] = 
{
    "^AUTHVER",    /* 获取数据锁版本AT^AUTHVER */
    "^DATALOCK",    /* 设置数据锁命令AT^DATALOCK */
    "^SN",    /* 产品整机条码号命令AT^SN */
};


const VOS_CHAR * MbbAtCmdFilterGetTable(VOS_VOID)
{
    return gszFilterCmdTable;
}


VOS_UINT32 MbbAtCmdFilterGetTableCount(VOS_VOID)
{
    return (sizeof(gszFilterCmdTable) / sizeof(gszFilterCmdTable[0]));
}


/******************************************************************************/
/***************************** MBB AT 一级白名单列表结束 **********************/
/******************************************************************************/


