#ifndef __HI_BBP_H__
#define __HI_BBP_H__ 
#include "mdrv_public.h"
#ifdef __cplusplus
extern "C" {
#endif
#define V7R5_BBP 
typedef enum{
    BBP_PWR_IRM,
    BBP_PWR_WTC,
    BBP_PWR_G1,
    BBP_PWR_G2,
    BBP_PWR_L ,
    BBP_PWR_BUTT
}BBP_PWR_ID_E;
#define BBP_CLK_MIN 0
#define BBP_CLK_MAX 28
#define BBP_PWR_MIN BBP_PWR_IRM
#define BBP_PWR_MAX BBP_PWR_L
#define BBP_VOTE_CLK_MIN 0
#define BBP_VOTE_CLK_MAX 26
#define BBP_VOTE_PWR_MIN BBP_PWR_IRM
#define BBP_VOTE_PWR_MAX BBP_PWR_G2
#define BBP_PWC_MODULE_MIN PWC_COMM_MODULE_BBP_DRX
#define BBP_PWC_MODULE_MAX PWC_COMM_MODULE_BBP_MEM
#define BBP_PWC_MODEM_MIN PWC_COMM_MODEM_0
#define BBP_PWC_MODEM_MAX PWC_COMM_MODEM_1
#define BBP_PWC_MODE_MIN PWC_COMM_MODE_GSM
#define BBP_PWC_MODE_MAX PWC_COMM_MODE_TDS
#define BBP_PWR_NUM (BBP_PWR_MAX-BBP_PWR_MIN+1)
#define BBP_CLK_NUM (BBP_CLK_MAX-BBP_CLK_MIN+1)
#define BBP_VOTE_PWR_NUM (BBP_VOTE_PWR_MAX-BBP_VOTE_PWR_MIN+1)
#define BBP_VOTE_CLK_NUM (BBP_VOTE_CLK_MAX-BBP_VOTE_CLK_MIN+1)
#define BBP_MODULE_NUM (BBP_PWC_MODULE_MAX-BBP_PWC_MODULE_MIN+1)
#define BBP_MODEM_NUM (BBP_PWC_MODEM_MAX-BBP_PWC_MODEM_MIN+1)
#define BBP_MODE_NUM (BBP_PWC_MODE_MAX-BBP_PWC_MODE_MIN+1)
#ifdef __cplusplus
}
#endif
#endif
