#ifndef __HI_BBP_DMA_H__
#define __HI_BBP_DMA_H__ 
#define BBP_DMA_BUSY_BIT_OFFSET 16
#define HI_BBP_FAST_CH0_BBP_ADDR_OFFSET 0x1230
#define HI_BBP_FAST_CH0_SOC_ADDR_OFFSET 0x1234
#define HI_BBP_FAST_CH0_CFG_OFFSET 0x1238
#define HI_BBP_FAST_CH0_CTL_OFFSET 0x123c
#endif
