#ifndef __SOC_ATE_H
#define __SOC_ATE_H 
#include <product_config.h>
#ifdef __cplusplus
extern "C" {
#endif
#ifdef ATE_VECTOR
#define ATE_VECTOR_VERSION 1
#define ATE_GPIO_GRP_NUM 10
#define ATE_GPIO_PINS_PER_GRP 8
#define ATE_GPIO_NONE 0xff
#define ATE_GPIO_VECTOR_GRP 8
#define ATE_GPIO_M3BOOT_ATE_INIT 8
#define ATE_GPIO_M3BOOT_UART0_INIT 9
#define ATE_GPIO_M3BOOT_DDR_INIT 10
#define ATE_GPIO_M3BOOT_CPYM3TOTCM 11
#define ATE_GPIO_M3BOOT_CPYFBOOTTOAXI 12
#define ATE_GPIO_M3BOOT_CASE_BEGIN ATE_GPIO_NONE
#define ATE_GPIO_M3BOOT_CASE_PASS ATE_GPIO_NONE
#define ATE_GPIO_M3BOOT_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_M3BOOT_DDR_WIN_CASE_OK 13
#define ATE_GPIO_M3BOOT_DDR_WIN_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_M3BOOT_DDR_RW_CASE_OK 14
#define ATE_GPIO_M3BOOT_DDR_RW_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_DDR_1 2
#define ATE_GPIO_DDR_2 3
#define ATE_GPIO_FBOOT_BOARD_INIT 16
#define ATE_GPIO_FBOOT_CPYPTABLT2SRAM 17
#define ATE_GPIO_FBOOT_CASE_BEGIN 18
#define ATE_GPIO_FBOOT_CASE_PASS 19
#define ATE_GPIO_FBOOT_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_FBOOT_CORESIGHT_CASE_OK 20
#define ATE_GPIO_FBOOT_CORESIGHT_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_FBOOT_CCPU_CACHE_CASE_OK 21
#define ATE_GPIO_FBOOT_CCPU_CACHE_CASE_FAIL ATE_GPIO_NONE
#define ATE_GPIO_ACORE_CASE_BEGIN 24
#define ATE_GPIO_ACORE_CASE_PASS 25
#define ATE_GPIO_ACORE_CASE_FAIL 26
#define ATE_GPIO_ACORE_CACHE_CASE_OK 27
#define ATE_GPIO_ACORE_CACHE_CASE_FAIL 28
#define ATE_GPIO_ACORE_MEMCPY_CASE_OK 29
#define ATE_GPIO_ACORE_MEMCPY_CASE_FAIL 30
#define ATE_GPIO_BAD_CHIP 56
#define ATE_GPIO_GOOD_CHIP ATE_GPIO_ACORE_CASE_PASS
#endif
#ifdef __cplusplus
}
#endif
#endif
