obj-y             += cmux_api_ifc.o
obj-y             += cmux_cmd.o
obj-y             += cmux_drv_ifc.o
obj-y             += cmux_framer.o
obj-y             += cmux_tgt_osal.o
obj-y             += cmux_udi_al.o