/*
 * ZLR96621L_SM2_Poland.c --
 *
 * This file contains profile data in byte format
 *
 * Project Info --
 *   File:   D:\Microsemi\Profile_Wizard_P2.5.0\ZLR96622_SM2_FULL.vpw
 *   Type:   Design for ZLR96822 SM2 Line Module Featuring the Le9662, Lite Coefficients
 *   Date:   Wednesday, January 28, 2015 11:38:02
 *   Device: VE960 Le9662_A
 *
 *   This file was generated with Profile Wizard Version: P2.5.0
 *
 * Project Comments --
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  Profile Wizard Coefficient Revision 2.9 Release Notes:
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  I. General:
 *  1. This release includes support for the following 44 countries:
 *  Argentina (AR), Austria (AT), Australia (AU), Belgium (BE), Brazil (BR), Bulgaria (BG), Canada (CA), Switzerland (CH),
 *  Chile (CL), China (CN), Czech Republic (CZ), Germany (DE), Denmark (DK), Ecuador (EC), Spain (ES), Finland (FI),
 *  France (FR), UK (GB), Greece (GR), Hong Kong SAR China (HK), Hungary (HU), Indonesia (ID), Ireland (IE), Israel (IL),
 *  India (IN), Iceland (IS), Italy (IT), Japan (JP), S. Korea (KR), Mexico (MX), Malaysia (MY), Netherlands (NL),
 *  Norway (NO), New Zealand (NZ), Poland (PL), Portugal (PT), Russian Federation (RU), Sweden (SE), Singapore (SG),
 *  Thailand (TH), Turkey (TK), Taiwan (TW), USA (US), and South Africa (ZA).
 *  2. The coefficients in this and all releases are provided for use only with the Microsemi VoicePath API-II (VP-API-II). Please refer 
 *  to the terms and conditions for licensing the software regarding terms and conditions of usage. These profiles are provided for 
 *  reference only with no guarantee whatsoever by Microsemi Corporation.
 *  3. This release is for the ZLR96822 SM2 Line Module based on the Le9662.
 *  
 *  II. Device Profiles:
 *  1. Two device profiles are included.  ZLR88822_ABS_47UH_DEVICE is intended for power supply designs using a 47uH inductor.
 *  ZLR88822_ABS_100UH_DEVICE is intended for use with a 100uH inductor.
 *  
 *  III. DC Profiles:
 *  1. The DC_FXS_VE960_ABS100V_DEF Profile is the default unless a country specific profile is selected. Example DC profile settings are
 *  provided for China, ETSI and the USA.
 *  
 *  IV. AC Profiles:
 *  1. FXS Coefficients assume -6dBr RX (Output from chipset) and 0dB TX relative gain levels.
 *  2. Supported countries not individually listed should use the default 600R profile AC_FXS_RF14_600R_DEF.
 *  4. AC FXS Coefficients assume the use of two 7 ohm series resistors or PTCs. Customers using other PTC resistance values (such as 
 *  25ohms or 50 ohms) should not use these AC coefficients and can request alternate ones from Microsemi.
 *  5. This release includes both Narrowband and Wideband coefficients. Note that the VE960 Series devices support per channel Narrowband or
 *  Wideband audio selection.
 *  
 *  V. Ring Profiles:
 *  1. RING_VE960_ABS100V_DEF is the default ringing profile and should be used for all countries which do not have a listed ringing profile.  
 *  The default ringing profile is set for a sine wave ringing with an amplitude of 50Vrms (70.7Vpk)with no DC bias and a frequency of 25 Hz 
 *  generated by fixed (non-tracking) supply.
 *  2. Most ringing profiles on the list are sinusoidal with an amplitude of 50Vrms with no DC bias generated by fixed (non-tracking) supply. 
 *  3. The ringing definitions may be changed based on the requirements of the target market as long as the total amplitude (AC + DC 
 *  components) does not exceed the limits set forth in the Le9662 data sheet.
 *  
 *  VI. Tone Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VII. Cadence Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VIII. Caller ID Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  IX. Metering Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  (c) Copyright 2013 Microsemi Corporation. All rights reserved.
 *  
 *  -----------------------------------------------------------------------------------------------------------------------------------------------------
 */

#include "ZLR96411L_SM2_POLAND.h"


/************** Device Profile **************/

/************** DC Profile **************/

/************** AC Profile **************/

/* AC FXS RF14 ETSI ES201 970 270R+750R//150nF Normal Coefficients */
const VpProfileDataType AC_FXS_RF14_ETSI[] =
{
  /* AC Profile */
 0xD5, 0x00, 0xEC, 0x4C, 0x01, 0x49, 0xCA, 0xE8, 0x98, 0x4A, 0xA1, 0x34,
 0xA2, 0xA2, 0xAC, 0x2C, 0xBB, 0x2B, 0xA4, 0x9A, 0x98, 0x92, 0x97, 0x9F,
 0x01, 0x8A, 0x9C, 0xD0, 0x2B, 0x20, 0x8F, 0x39, 0x2A, 0xBB, 0xA4, 0x24,
 0xB2, 0xBC, 0x4B, 0x26, 0x88, 0xA3, 0xC0, 0xC2, 0x27, 0xBA, 0x3E, 0xAC,
 0xAF, 0xB4, 0x26, 0x24, 0x3F, 0x82, 0xA8, 0x71, 0x80, 0xA9, 0xF0, 0x50,
 0x00, 0x86, 0xC3, 0x5F, 0x32, 0x98, 0x03, 0xA1, 0xAA, 0x23, 0xB3, 0x2C,
 0x4B, 0x55, 0x25, 0x60, 0x96, 0xF2, 0xC1, 0x00
};

/* AC FXS RF14 ETSI ES201 970 270R+750R//150nF Wideband Coefficients */
const VpProfileDataType AC_FXS_RF14_WB_ETSI[] =
{
  /* AC Profile */
 0xAA, 0x00, 0x9C, 0x4C, 0x01, 0x49, 0xCA, 0xE0, 0x98, 0xAA, 0xA3, 0x6B,
 0x22, 0x43, 0xA2, 0xAC, 0xBF, 0x22, 0xA6, 0x9A, 0x01, 0x90, 0x01, 0x01,
 0x90, 0x8A, 0x2E, 0x01, 0xBA, 0x10, 0xA2, 0x3A, 0xBA, 0xE9, 0xAA, 0xB5,
 0x2A, 0xBC, 0xAF, 0x97, 0x88, 0xAB, 0xC0, 0x4A, 0xBE, 0xBA, 0x9F, 0xC3,
 0xAF, 0x3A, 0x3F, 0xCD, 0xA7, 0x82, 0xC8, 0x71, 0x80, 0x69, 0xF0, 0x50,
 0x00, 0x86, 0xBA, 0x52, 0xB2, 0xBA, 0x12, 0x42, 0x4A, 0x2A, 0x33, 0xBA,
 0x33, 0x34, 0x4B, 0x40, 0x96, 0xB2, 0xA0, 0x00
};

/************** Ringing Profile **************/

/************** Tone Profile **************/

/* Poland Dial Tone  */
const VpProfileDataType T_DL_PL[] =
{
/* Sig gen A = 425.17 Hz at -4.00 dBm0 */
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x02, 0x00,       /* Tone Profile for Le9662_A device */
   0x0F,                   /* Profile length = 15 + 4 = 19 bytes */
   0x02,                   /* Profile format version = 2 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD2, 0x00, 0x00, 0x00, /* Signal Generator A, B, Bias Parameters */
         0x04, 0x89, 0x38,
         0x43, 0x00, 0x00,
         0x13, 0xF7,
/* Formatted Parameters Section -------------------------------------------- */
   0x01                    /* FM_EN = 0; WB = 0; Active Generators: A */
};

/* Poland Ringback Tone  */
const VpProfileDataType T_RG_PL[] =
{
/* Sig gen A = 425.17 Hz at -4.00 dBm0 */
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x02, 0x00,       /* Tone Profile for Le9662_A device */
   0x0F,                   /* Profile length = 15 + 4 = 19 bytes */
   0x02,                   /* Profile format version = 2 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD2, 0x00, 0x00, 0x00, /* Signal Generator A, B, Bias Parameters */
         0x04, 0x89, 0x38,
         0x43, 0x00, 0x00,
         0x13, 0xF7,
/* Formatted Parameters Section -------------------------------------------- */
   0x01                    /* FM_EN = 0; WB = 0; Active Generators: A */
};

/* Poland Busy Tone  */
const VpProfileDataType T_BS_PL[] =
{
/* Sig gen A = 425.17 Hz at -4.00 dBm0 */
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x02, 0x00,       /* Tone Profile for Le9662_A device */
   0x0F,                   /* Profile length = 15 + 4 = 19 bytes */
   0x02,                   /* Profile format version = 2 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD2, 0x00, 0x00, 0x00, /* Signal Generator A, B, Bias Parameters */
         0x04, 0x89, 0x38,
         0x43, 0x00, 0x00,
         0x13, 0xF7,
/* Formatted Parameters Section -------------------------------------------- */
   0x01                    /* FM_EN = 0; WB = 0; Active Generators: A */
};

/* Poland Call Waiting Tone  */
const VpProfileDataType T_CW_PL[] =
{
/* Sig gen A = 425.17 Hz at -7.00 dBm0 */
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x02, 0x00,       /* Tone Profile for Le9662_A device */
   0x0F,                   /* Profile length = 15 + 4 = 19 bytes */
   0x02,                   /* Profile format version = 2 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD2, 0x00, 0x00, 0x00, /* Signal Generator A, B, Bias Parameters */
         0x04, 0x89, 0x27,
         0xD5, 0x00, 0x00,
         0x13, 0xF7,
/* Formatted Parameters Section -------------------------------------------- */
   0x01                    /* FM_EN = 0; WB = 0; Active Generators: A */
};

/* Poland Congestion Tone */
const VpProfileDataType T_CG_PL[] =
{
/* Sig gen A = 425.17 Hz at -4.00 dBm0 */
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x02, 0x00,       /* Tone Profile for Le9662_A device */
   0x0F,                   /* Profile length = 15 + 4 = 19 bytes */
   0x02,                   /* Profile format version = 2 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD2, 0x00, 0x00, 0x00, /* Signal Generator A, B, Bias Parameters */
         0x04, 0x89, 0x38,
         0x43, 0x00, 0x00,
         0x0E, 0x22,
/* Formatted Parameters Section -------------------------------------------- */
   0x01                    /* FM_EN = 0; WB = 0; Active Generators: A */
};

/************** Cadence Profile **************/

/* Poland Ringing Signal Cadence */
const VpProfileDataType CR_PL[] =
{
  /* Cadence Profile */
 0x00, 0x08, 0x00, 0x12, 0x00, 0x00, 0x00, 0x0E, 0x01, 0x07, 0x20, 0xC8,
 0x01, 0x00, 0x20, 0x28, 0x01, 0x05, 0x22, 0xF8, 0x40, 0x00
};

/* Poland Dial Tone Cadence */
const VpProfileDataType CT_DL_PL[] =
{
  /* Cadence Profile */
 0x00, 0x03, 0x00, 0x08, 0x00, 0x00, 0x00, 0x04, 0x00, 0x8F, 0x20, 0x00
};

/* Poland Ringback Tone Cadence */
const VpProfileDataType CT_RB_PL[] =
{
  /* Cadence Profile */
 0x00, 0x03, 0x00, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x8F, 0x20, 0xC8,
 0x00, 0x80, 0x23, 0x20, 0x40, 0x00
};

/* Poland Busy Tone Cadence */
const VpProfileDataType CT_BS_PL[] =
{
  /* Cadence Profile */
 0x00, 0x03, 0x00, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x8F, 0x20, 0x64,
 0x00, 0x80, 0x20, 0x64, 0x40, 0x00
};

/* Poland Call Waiting Cadence */
const VpProfileDataType CT_CW_PL[] =
{
  /* Cadence Profile */
 0x00, 0x03, 0x00, 0x16, 0x00, 0x00, 0x00, 0x12, 0x00, 0x8F, 0x20, 0x1E,
 0x00, 0x80, 0x20, 0x1E, 0x00, 0x8F, 0x20, 0x1E, 0x00, 0x80, 0x23, 0x20,
 0x40, 0x01
};

/* Poland Congestion Cadence */
const VpProfileDataType CT_CG_PL[] =
{
  /* Cadence Profile */
 0x00, 0x03, 0x00, 0x0E, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x8F, 0x20, 0x64,
 0x00, 0x8F, 0x20, 0x64, 0x40, 0x00
};

/************** Caller ID Profile **************/

/************** Metering_Profile **************/

/* end of file ZLR96621L_SM2_Poland.c */
