/*
 * ZLR96621L_SM2_Poland.h --
 *
 * This header file exports the Profile data types
 *
 * Project Info --
 *   File:   D:\Microsemi\Profile_Wizard_P2.5.0\ZLR96622_SM2_FULL.vpw
 *   Type:   Design for ZLR96822 SM2 Line Module Featuring the Le9662, Lite Coefficients
 *   Date:   Wednesday, January 28, 2015 11:38:02
 *   Device: VE960 Le9662_A
 *
 *   This file was generated with Profile Wizard Version: P2.5.0
 *
 * Project Comments --
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  Profile Wizard Coefficient Revision 2.9 Release Notes:
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  I. General:
 *  1. This release includes support for the following 44 countries:
 *  Argentina (AR), Austria (AT), Australia (AU), Belgium (BE), Brazil (BR), Bulgaria (BG), Canada (CA), Switzerland (CH),
 *  Chile (CL), China (CN), Czech Republic (CZ), Germany (DE), Denmark (DK), Ecuador (EC), Spain (ES), Finland (FI),
 *  France (FR), UK (GB), Greece (GR), Hong Kong SAR China (HK), Hungary (HU), Indonesia (ID), Ireland (IE), Israel (IL),
 *  India (IN), Iceland (IS), Italy (IT), Japan (JP), S. Korea (KR), Mexico (MX), Malaysia (MY), Netherlands (NL),
 *  Norway (NO), New Zealand (NZ), Poland (PL), Portugal (PT), Russian Federation (RU), Sweden (SE), Singapore (SG),
 *  Thailand (TH), Turkey (TK), Taiwan (TW), USA (US), and South Africa (ZA).
 *  2. The coefficients in this and all releases are provided for use only with the Microsemi VoicePath API-II (VP-API-II). Please refer 
 *  to the terms and conditions for licensing the software regarding terms and conditions of usage. These profiles are provided for 
 *  reference only with no guarantee whatsoever by Microsemi Corporation.
 *  3. This release is for the ZLR96822 SM2 Line Module based on the Le9662.
 *  
 *  II. Device Profiles:
 *  1. Two device profiles are included.  ZLR88822_ABS_47UH_DEVICE is intended for power supply designs using a 47uH inductor.
 *  ZLR88822_ABS_100UH_DEVICE is intended for use with a 100uH inductor.
 *  
 *  III. DC Profiles:
 *  1. The DC_FXS_VE960_ABS100V_DEF Profile is the default unless a country specific profile is selected. Example DC profile settings are
 *  provided for China, ETSI and the USA.
 *  
 *  IV. AC Profiles:
 *  1. FXS Coefficients assume -6dBr RX (Output from chipset) and 0dB TX relative gain levels.
 *  2. Supported countries not individually listed should use the default 600R profile AC_FXS_RF14_600R_DEF.
 *  4. AC FXS Coefficients assume the use of two 7 ohm series resistors or PTCs. Customers using other PTC resistance values (such as 
 *  25ohms or 50 ohms) should not use these AC coefficients and can request alternate ones from Microsemi.
 *  5. This release includes both Narrowband and Wideband coefficients. Note that the VE960 Series devices support per channel Narrowband or
 *  Wideband audio selection.
 *  
 *  V. Ring Profiles:
 *  1. RING_VE960_ABS100V_DEF is the default ringing profile and should be used for all countries which do not have a listed ringing profile.  
 *  The default ringing profile is set for a sine wave ringing with an amplitude of 50Vrms (70.7Vpk)with no DC bias and a frequency of 25 Hz 
 *  generated by fixed (non-tracking) supply.
 *  2. Most ringing profiles on the list are sinusoidal with an amplitude of 50Vrms with no DC bias generated by fixed (non-tracking) supply. 
 *  3. The ringing definitions may be changed based on the requirements of the target market as long as the total amplitude (AC + DC 
 *  components) does not exceed the limits set forth in the Le9662 data sheet.
 *  
 *  VI. Tone Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VII. Cadence Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VIII. Caller ID Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  IX. Metering Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  (c) Copyright 2013 Microsemi Corporation. All rights reserved.
 *  
 *  -----------------------------------------------------------------------------------------------------------------------------------------------------
 */

#ifndef ZLR96621L_SM2_POLAND_H
#define ZLR96621L_SM2_POLAND_H

#ifdef VP_API_TYPES_H
#include "vp_api_types.h"
#else
typedef unsigned char VpProfileDataType;
#endif


/************** Device Profile **************/

/************** DC Profile **************/

/************** AC Profile **************/
extern const VpProfileDataType AC_FXS_RF14_ETSI[];   /* AC FXS RF14 ETSI ES201 970 270R+750R//150nF Normal Coefficients */
extern const VpProfileDataType AC_FXS_RF14_WB_ETSI[];/* AC FXS RF14 ETSI ES201 970 270R+750R//150nF Wideband Coefficients */

/************** Ringing Profile **************/

/************** Tone Profile **************/
extern const VpProfileDataType T_DL_PL[];            /* Poland Dial Tone  */
extern const VpProfileDataType T_RG_PL[];            /* Poland Ringback Tone  */
extern const VpProfileDataType T_BS_PL[];            /* Poland Busy Tone  */
extern const VpProfileDataType T_CW_PL[];            /* Poland Call Waiting Tone  */
extern const VpProfileDataType T_CG_PL[];            /* Poland Congestion Tone */

/************** Cadence Profile **************/
extern const VpProfileDataType CR_PL[];              /* Poland Ringing Signal Cadence */
extern const VpProfileDataType CT_DL_PL[];           /* Poland Dial Tone Cadence */
extern const VpProfileDataType CT_RB_PL[];           /* Poland Ringback Tone Cadence */
extern const VpProfileDataType CT_BS_PL[];           /* Poland Busy Tone Cadence */
extern const VpProfileDataType CT_CW_PL[];           /* Poland Call Waiting Cadence */
extern const VpProfileDataType CT_CG_PL[];           /* Poland Congestion Cadence */

/************** Caller ID Profile **************/

/************** Metering_Profile **************/

#endif /* ZLR96621L_SM2_POLAND_H */

