-include $(srctree)/drivers/hisi/modem/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

obj-$(CONFIG_DSP_BALONG)	+= bsp_dsp.o
obj-$(CONFIG_DSP_BALONG)	+= dsp_balong.o
subdir-ccflags-y := -Werror