#
# Makefile for the modem drivers.
#
-include $(BALONG_TOPDIR)/modem/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

#drv oam ps taf move to hisi/makefile

#obj-y				+= drv/

#obj-$(CONFIG_BALONG_OAM_PS)  += oam/ ps/ taf/


