/*
 * ZLR96621L_SM2_CHINA.h --
 *
 * This header file exports the Profile data types
 *
 * Project Info --
 *   File:   C:\Microsemi\VoicePath API-II P2.22.0\coefficient_sets\VE960\ZLR96621_ABS\ZLR96621L_SM2_FULL.vpw
 *   Type:   Design for ZLR96621L SM2 Line Module Featuring the Le9662, Lite Coefficients
 *   Date:   Friday, June 20, 2014 17:04:28
 *   Device: VE960 Le9662_A
 *
 *   This file was generated with Profile Wizard Version: P2.5.0
 *
 * Project Comments --
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  Profile Wizard Coefficient Revision 2.9 Release Notes:
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  I. General:
 *  1. This release includes support for the following 44 countries:
 *  Argentina (AR), Austria (AT), Australia (AU), Belgium (BE), Brazil (BR), Bulgaria (BG), Canada (CA), Switzerland (CH),
 *  Chile (CL), China (CN), Czech Republic (CZ), Germany (DE), Denmark (DK), Ecuador (EC), Spain (ES), Finland (FI),
 *  France (FR), UK (GB), Greece (GR), Hong Kong SAR China (HK), Hungary (HU), Indonesia (ID), Ireland (IE), Israel (IL),
 *  India (IN), Iceland (IS), Italy (IT), Japan (JP), S. Korea (KR), Mexico (MX), Malaysia (MY), Netherlands (NL),
 *  Norway (NO), New Zealand (NZ), Poland (PL), Portugal (PT), Russian Federation (RU), Sweden (SE), Singapore (SG),
 *  Thailand (TH), Turkey (TK), Taiwan (TW), USA (US), and South Africa (ZA).
 *  2. The coefficients in this and all releases are provided for use only with the Microsemi VoicePath API-II (VP-API-II). Please refer 
 *  to the terms and conditions for licensing the software regarding terms and conditions of usage. These profiles are provided for 
 *  reference only with no guarantee whatsoever by Microsemi Corporation.
 *  3. This release is for the ZLR96621L SM2 Line Module based on the Le9662.
 *  
 *  II. Device Profile:
 *  1. The default settings for the Device Profiles are:
 *         PCLK = 8192 kHz
 *         PCM Transmit Edge = Positive
 *         Transmit Time Slot = 6 (for ZSI)
 *         Receive Time Slot = 0
 *         Interrupt Mode = Open Drain
 *         Switching Regulator Y Control Mode = Single
 *         Switching Regulator Y Voltage = 27V or 30V
 *         Switching Regulator Z Control Mode = Single
 *         Switching Regulator Z Voltage = 81V or 90V
 *         IO21 Pin Mode = Digital
 *         IO22 Pin Mode = Analog Voltage Sense
 *      
 *  2. The settings may be changed by the user as necessary.  Please refer to the VE960 and VP-API-II documentation for information 
 *  about the supported settings.
 *  
 *  II. DC Profiles:
 *  1. The DC_FXS_VE960_ABS100V_DEF Profile is the default unless a country specific profile is selected. Example DC profile settings are
 *  provided for China, ETSI and the USA.
 *  
 *  III. AC Profiles:
 *  1. FXS Coefficients assume -6dBr RX (Output from chipset) and 0dB TX relative gain levels.
 *  2. Supported countries not individually listed should use the default 600R profile AC_FXS_RF14_600R_DEF.
 *  4. AC FXS Coefficients assume the use of two 7 ohm series resistors or PTCs. Customers using other PTC resistance values (such as 
 *  25ohms or 50 ohms) should not use these AC coefficients and can request alternate ones from Microsemi.
 *  5. This release includes both Narrowband and Wideband coefficients. Note that the VE960 Series devices support per channel Narrowband or
 *  Wideband audio selection.
 *  
 *  IV. Ring Profiles:
 *  1. RING_VE960_ABS100V_DEF is the default ringing profile and should be used for all countries which do not have a listed ringing profile.  
 *  The default ringing profile is set for a sine wave ringing with an amplitude of 50Vrms (70.7Vpk)with no DC bias and a frequency of 25 Hz 
 *  generated by fixed (non-tracking) supply.
 *  2. Most ringing profiles on the list are sinusoidal with an amplitude of 50Vrms with no DC bias generated by fixed (non-tracking) supply. 
 *  3. The ringing definitions may be changed based on the requirements of the target market as long as the total amplitude (AC + DC 
 *  components) does not exceed the limits set forth in the Le9662 data sheet.
 *  
 *  V. Tone Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VI. Cadence Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VII. Caller ID Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VIII. Metering Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  (c) Copyright 2013 Microsemi Corporation. All rights reserved.
 *  
 *  -----------------------------------------------------------------------------------------------------------------------------------------------------
 */
 
#ifndef ZLR96411L_SM2_CHINA_H
#define ZLR96411L_SM2_CHINA_H

#ifdef VP_API_TYPES_H
#include "vp_api_types.h"
#else
typedef unsigned char VpProfileDataType;
#endif


#include "mbb_config.h"
#include "product_config.h"
/************** Device Profile **************/
extern VpProfileDataType ZLR96411L_ABS81V_DEVICE[];/* Device Configuration Data - Le9641 100V ABS (-81V/-27V) */

/************** DC Profile **************/
extern VpProfileDataType DC_FXS_MISLIC_ABS100V_DEF[];/* DC FXS Defaults - Use for all countries unless country file exists - 23mA Current Feed */

/************** AC Profile **************/
extern VpProfileDataType AC_FXS_RF14_600R_DEF[];/* AC FXS RF14 600R Normal Coefficients (Default)  */
extern VpProfileDataType AC_FXS_RF14_CN[];     /* AC FXS RF14 China 200R+680R//100nF Normal Coefficients */
extern VpProfileDataType AC_FXS_RF14_WB_CN[];  /* AC FXS RF14 China 200R+680R//100nF Wideband Coefficients */

/************** Ringing Profile **************/
extern VpProfileDataType RING_VE960_ABS100V_DEF[];/* Default Ringing 25Hz 50Vrms Fixed, AC Trip - Use for all countries unless country profile exists */

/************** Tone Profile **************/
extern VpProfileDataType T_DL_CN[];            /* China Dial Tone  */
extern VpProfileDataType T_RB_CN[];            /* China Ringback Tone  */
extern VpProfileDataType T_BS_CN[];            /* China Busy Tone  */
extern VpProfileDataType T_CW_CN[];            /* China Call Waiting Tone */
extern VpProfileDataType T_CG_CN[];            /* China Congestion Tone */

/************** Cadence Profile **************/
extern VpProfileDataType CR_FSK_CN[];          /* China Ringing FSK Cadence */
extern VpProfileDataType CR_DTMF_CN[];         /* China Ringing DTMF Cadence */
extern VpProfileDataType CT_DL_CN[];           /* China Dial Tone Cadence */
extern VpProfileDataType CT_RB_CN[];           /* China Ringback Tone Cadence */
extern VpProfileDataType CT_BS_CN[];           /* China Busy Tone Cadence */
extern VpProfileDataType CT_CW_CN[];           /* China Call Waiting Cadence */
extern VpProfileDataType CT_CG_CN[];           /* China Congestion Cadence */

/************** Caller ID Profile **************/
extern VpProfileDataType CID_TYPE_DTMF_CN[];       /* China Caller ID (Type 1 - On-Hook) - ETSI DTMF */
extern VpProfileDataType CID_TYPE1_CN[];       /* China Caller ID (Type 1 - On-Hook) - Telcordia FSK */
extern VpProfileDataType CID_TYPE2_CN[];       /* China Caller ID (Type 2 - Off-Hook) - Telcordia FSK */

extern VpProfileDataType CT_ALARM_CN[];
extern VpProfileDataType T_ALARM_CN[];

extern VpProfileDataType CT_SVCEN_CN[];
extern VpProfileDataType T_SVCEN_CN[];
extern VpProfileDataType T_FAULT_CN[];

extern VpProfileDataType CT_SVCDIS_CN[];
extern VpProfileDataType T_SVCDIS_CN[];
extern VpProfileDataType CT_FAULT_CN[];

extern VpProfileDataType T_DL_VM_CN[];         /* China Voice Mail Dial Tone */
extern VpProfileDataType CT_DL_VM_CN[];        /* China Voice Mail Cadence */

/************** Metering_Profile **************/

#endif /* ZLR96411L_SM2_CHINA_H */

