#
# Makefile for wifi_arp_cheap_protect
#
-include $(BALONG_TOPDIR)/modem/config/product/$(OBB_PRODUCT_NAME)/config/balong_product_config.mk

ifeq ($(MBB_WIFI_CHIP1),bcm4352)
    obj-y				+= bcm4352/
endif

ifeq ($(MBB_WIFI_CHIP1),bcm4360)
    obj-y				+= bcm4352/
endif

ifeq ($(MBB_WIFI_CHIP1),bcm43217)
    obj-y				+= bcm4352/
endif

